### ISSUE TITLE
issue with 2 levels' leafref

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1442]
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
[Description of the bug or feature]
in microwave domain, we have yang model ietf-microwave-radio-link@2018-10-03.yang. it defined 
1. carrier-termination, which augment to ietf-interfaces/interface. 
2. xpic-pairs, which is top level container, internally have leafref to carrier-termination interface
3. radio-link-terminal which augment to ietf-interfaces/interface and leafref to both carrier-termination and xpic-pairs.  the related yang file and xml data files are attached.

when i import data,  it report some error.

### Steps to Reproduce
1.  install the yang file
2.  import ct.xml
sysrepocfg --import=ct.xml --datastore=startup ietf-interfaces
The new configuration was successfully applied.
[ERR] Failed to copy ns
[ERR] Failed print config-change notif to string
[ERR] Failed to save event notification
[WRN] Error by processing of the message: Sysrepo-internal error.

3. import xpic.xml
sysrepocfg --import=xpic.xml --datastore=startup ietf-microwave-radio-link
The new configuration was successfully applied.

4. import rlt.xml
sysrepocfg --import=rlt.xml --datastore=startup ietf-interfaces
[ERR] Input data are not valid: Leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" of value "CT 1/4/2" points to a non-existing leaf. (/ietf-microwave-radio
-link:xpic-pairs/xpic-pair[name='XPIC 1/4/1']/members[.='CT 1/4/2'])
Errors were encountered during importing. Cancelling the operation.

**Expected behavior:**
imported without error

**Actual behavior:**
see step 4 above

### Versions
sysrepod - sysrepo daemon, version 0.7.7
yanglint 0.16.105

### Attachments
sysrepoctl [-l](url)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpat
h
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:root           | 666         |                               | arbitrary-names pre-provisioning if-mib
iana-if-type               | 2018-07-03 | Installed   |                     |             |                               |
ietf-microwave-types       | 2018-10-03 | Installed   |                     |             |                               |
ietf-interface-protection  | 2018-06-30 | Installed   |                     |             |                               |
ietf-microwave-radio-link  | 2018-10-03 | Installed   | root:root           | 666         |                               | xpic tdm

Thanks!
[sysrepoinfo.zip](https://github.com/sysrepo/sysrepo/files/2956386/sysrepoinfo.zip)

it is a tar file, i change the postfix to zip in order to upload here.

**Comment by michalvasko** [comment]
Hi,
I cannot help you with the first error because I had to remove some data from the XML files in namespace `urn:com:ericsson:yang:mini-link:radio-link` for which you have not provided the module and when I did, the error did not appear.

As for the last import error, it is expected because you are trying to replace the whole `ietf-interfaces` datastore so you are removing the necessary leafref targets. Use `--merge` operation instead (but update *sysrepo* because there was a problem with validation in this operation that I have fixed).

Regards,
Michal

**Comment by GuoyouZhang** [comment]
thank you very much!
by the way will the sysrepocfg support importing multiple modules, so that i don't need to split my xml file into multiple according to the module name?

**Comment by GuoyouZhang** [comment]
still have same issue in my test
 sysrepocfg --import=ct.xml --datastore=startup ietf-interfaces
 sysrepocfg --import=xpic.xml --datastore=startup ietf-microwave-radio-link
the above two commands are ok.

 sysrepocfg --merge=rlt.xml --datastore=startup ietf-interfaces
[ERR] Input data are not valid: Leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" of value "CT 1/4/2" points to a non-existing leaf. (/ietf-microwave-radio-link:xpic-pairs/xpic-pair[name='XPIC 1/4/1']/members[.='CT 1/4/2'])
Errors were encountered during importing. Cancelling the operation.

**Comment by michalvasko** [comment]
Hi,
just updating and compiling *sysrepo* should be enough.
```
./src/sysrepoctl -l
ietf-microwave-radio-link  | 2018-10-03 | Installed   | root:root           | 666         |                               | xpic tdm
ietf-interfaces            | 2018-02-20 | Implemented | root:root           | 666         |                               | arbitrary-names pre-provisioning if-mib
ietf-interface-protection  | 2018-06-30 | Imported    |                     |             |                               |
ietf-microwave-types       | 2018-10-03 | Installed   |                     |             |                               |
iana-if-type               | 2018-07-03 | Imported    |                     |             |                               |
```
then
```
# ./src/sysrepocfg -i../../../Downloads/sysrepolog/ct.xml -dstartup ietf-interfaces
The new configuration was successfully applied.
# ./src/sysrepocfg -i../../../Downloads/sysrepolog/xpic.xml -dstartup ietf-microwave-radio-link
The new configuration was successfully applied.
# ./src/sysrepocfg -m../../../Downloads/sysrepolog/rlt.xml -dstartup ietf-interfaces
The new configuration was successfully applied.
```

Make sure you are using the updated *sysrepocfg*, do not forget to install it. Also, the change is only in `devel`, on the off chance you are using `master`.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
I think i use the right version, because it support merge
sysrepocfg -h |grep merge
  -m, --merge <path>           Flag used to merge a configuration from a supplied file
     sysrepocfg --merge=/tmp/backup.json --format=json ietf-interfaces
and I also checkout devel branch and re-do the test, but got same result.
i see your sysrepoctl -l only show the related module, but in my case
sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users radius
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:root           | 666         |                               | arbitrary-names pre-provisioning if-mib
iana-if-type               | 2018-07-03 | Installed   |                     |             |                               |
ietf-microwave-types       | 2018-10-03 | Installed   |                     |             |                               |
ietf-interface-protection  | 2018-06-30 | Installed   |                     |             |                               |
ietf-microwave-radio-link  | 2018-10-03 | Installed   | root:root           | 666         |                               | xpic tdm
[yang.zip](https://github.com/sysrepo/sysrepo/files/2965659/yang.zip)


but i guess it should not be a problem, right
=============== here is my steps=========
git clone https://github.com/sysrepo/sysrepo.git
cd sysrepo/
git checkout origin/devel
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE:String="Release" -DENABLE_TESTS=OFF -DREPOSITORY_LOC:PATH=/etc/sysrepo -DBUILD_EXAMPLES=0 ..
make
make install
ldconfig
sysrepod -d 2 &
./install-yang.sh
sysrepocfg -ict.xml -dstartup ietf-interfaces
sysrepocfg -ixpic.xml -dstartup ietf-microwave-radio-link
sysrepocfg -irlt.xml -dstartup ietf-interfaces

**Comment by michalvasko** [comment]
Before I try it again, you still have `-i` in your last step, did you really use `-i` or `-m`?

Regards,
Michal

**Comment by GuoyouZhang** [comment]
sorry, now i test it with -m
sysrepocfg -mrlt.xml -dstartup ietf-interfaces
[ERR] libyang error: Leafref "/ietf-microwave-radio-link:xpic-pairs/ietf-microwave-radio-link:xpic-pair/ietf-microwave-radio-link:name" of value "XPIC 1/4/1" points to a non-existing leaf.
[ERR] libyang error: Leafref "/ietf-microwave-radio-link:xpic-pairs/ietf-microwave-radio-link:xpic-pair/ietf-microwave-radio-link:name" of value "XPIC 1/4/1" points to a non-existing leaf.
[ERR] Validation after merging failed
[ERR] Commit operation failed with 1 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] /ietf-interfaces:interfaces/interface[name='RLT 1/4/1']/ietf-microwave-radio-link:xpic-pairs[.='XPIC 1/4/1'] : Leafref "/ietf-microwave-radio-link:xpic-pairs/ietf-microwave-radio-link:xpic-pair/ietf-microwave-radio-link:name" of value "XPIC 1/4/1" points to a non-existing leaf.
Errors were encountered during importing. Cancelling the operation.

**Comment by michalvasko** [comment]
Hi,
it works just fine for me, having followed your steps. *sysrepocfg* supported merge operation for a long time but there was a problem in validation that I have fixed, so my guess is that you are somehow not using this fixed version. Best would be to completely reinstall *sysrepo* (`devel`) and try again.

As for cleaning the data, you can manually edit (make it empty) them using commands such as this
```
sysrepocfg -dstartup -evim -fxml ietf-interfaces
```

Regards,
Michal

**Comment by GuoyouZhang** [comment]
i try it from scratch, still have issue as above.  but one change i noticed is that,  following errors disappeared. 
ERR] Failed to copy ns
[ERR] Failed print config-change notif to string
[ERR] Failed to save event notification

So when will you merge devel to master?  maybe good to try the master again once you merge the fix.

Thanks!
Guoyou

**Comment by michalvasko** [comment]
Hi,
I am not sure when the next merge will be, several weeks I suppose. The errors disappeared because you removed the data from the Ericsson module that were causing it. It is still a bug but if I cannot reproduce it, I am unable to fix it an the module is probably not public.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
did you use latest libyang?  I'm thinking what is difference between your env and mine.

**Comment by michalvasko** [comment]
Hi,
I did but that should not matter at all, I believe the problem is only in `sysrepocfg` itself.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
Hi Michal

is that possible to use my docker file to reproduce the issue? 
following commands are the steps after run the images built by my docker file
[Dockerfile.txt](https://github.com/sysrepo/sysrepo/files/3024223/Dockerfile.txt)

      sysrepod &
      export http_proxy=http://selnproxy.mo.sw.ericsson.se:8080/
      export https_proxy=http://selnproxy.mo.sw.ericsson.se:8080/
      wget https://github.com/sysrepo/sysrepo/files/2965666/yang.zip
      mv yang.zip yang.tar
      tar vxf yang.tar


      cd yang
     ./install-yang.sh
     sysrepocfg -ict.xml -dstartup ietf-interfaces
     sysrepocfg -ixpic.xml -dstartup ietf-microwave-radio-link
     sysrepocfg -mrlt.xml -dstartup ietf-interfaces


BR,
guoyou

**Comment by GuoyouZhang** [comment]
btw, when i test it by netconf/netopeer2, i got same issue:

[ERR] Get items failed for '/ietf-interfaces:interfaces/interface', session id=944236714.
[ERR] libyang error: Leafref "/ietf-microwave-radio-link:xpic-pairs/ietf-microwave-radio-link:xpic-pair/ietf-microwave-radio-link:name" of value "XPIC 1/4/1" points to a non-existing leaf.
[ERR] libyang error: Leafref "/ietf-microwave-radio-link:xpic-pairs/ietf-microwave-radio-link:xpic-pair/ietf-microwave-radio-link:name" of value "XPIC 1/4/1" points to a non-existing leaf.
[ERR] Validation after merging failed

**Comment by michalvasko** [comment]
Hi,
when I used your `Dockerfile` I managed to reproduce it. The issue is having `sysrepod` running while doing these changes, it worked for me even in *docker* when I did not start `sysrepod` at the beginning.

However, it should not make a difference and it should work independently of `sysrepod` running or not. It is difficult to debug so I am not sure when I will be able to properly fix this.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
good, at least you know the issue.  i don't know sysrepocfg can be used without sysrepod started

BR,
guoyou

**Comment by GuoyouZhang** [comment]
Hi Michal,

i'm trying to fix this issue now,  so i review the function: dm_validate_data_info(),  and i see that it call lyd_validate_modules(&info->node, &info->schema->module, 1, LYD_....  )  with 1 module only.
in my case, there are 2 modules ietf-interface and ietf-microwave-radio-link in one netconf transaction.  do you think is that the place that i need to dig out?

BR,
guoyou

**Comment by GuoyouZhang** [comment]
good news, looks like it works with netopeer2 now, but i will test further:)
