### ISSUE TITLE
TSAN: data race in notifications with custom event loop

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1450]
We have a custom event loop implementation that is based on libev. A test case which sends notifications from a background thread ends up with the following report from TSAN:
```
2019-03-25 09:36:24.392001 | w | WARNING: ThreadSanitizer: data race (pid=917)
2019-03-25 09:36:24.392098 | w |   Write of size 4 at 0x7b1800003470 by thread T12:
2019-03-25 09:36:24.392340 | w |     #0 sr_msg_free /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:595 (libsysrepo.so.0.7+0x998c0)
2019-03-25 09:36:24.392573 | w |     #1 cm_out_msg_process /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1756 (libsysrepo.so.0.7+0xcb519)
2019-03-25 09:36:24.392830 | w |     #2 cm_msg_enqueue_cb /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1819 (libsysrepo.so.0.7+0xb34c6)
2019-03-25 09:36:24.392929 | w |     #3 ev_invoke_pending ??:? (libev.so.4+0x4f72)
2019-03-25 09:36:24.393172 | w |     #4 cm_event_loop_threaded /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1891 (libsysrepo.so.0.7+0xb41cb)
2019-03-25 09:36:24.393208 | w |
2019-03-25 09:36:24.393333 | w |   Previous write of size 4 at 0x7b1800003470 by thread T8:
2019-03-25 09:36:24.393555 | w |     #0 sr_msg_free /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:595 (libsysrepo.so.0.7+0x998c0)
2019-03-25 09:36:24.393805 | w |     #1 rp_msg_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3687 (libsysrepo.so.0.7+0xdec92)
2019-03-25 09:36:24.394046 | w |     #2 rp_worker_thread_execute /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3769 (libsysrepo.so.0.7+0xd7dde)
2019-03-25 09:36:24.394090 | w |
2019-03-25 09:36:24.394223 | w |   Location is heap block of size 88 at 0x7b1800003420 allocated by thread T11:
2019-03-25 09:36:24.394345 | w |     #0 calloc ??:? (test_sysrepo-notifications+0x49c328)
2019-03-25 09:36:24.394565 | w |     #1 sr_mem_new /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:159 (libsysrepo.so.0.7+0x954b2)
2019-03-25 09:36:24.394828 | w |     #2 rp_subscribe_req_process /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:1832 (libsysrepo.so.0.7+0xfd0e8)
2019-03-25 09:36:24.395057 | w |     #3 rp_req_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3502 (libsysrepo.so.0.7+0xe043f)
2019-03-25 09:36:24.395299 | w |     #4 rp_msg_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3668 (libsysrepo.so.0.7+0xde8fe)
2019-03-25 09:36:24.395539 | w |     #5 rp_worker_thread_execute /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3769 (libsysrepo.so.0.7+0xd7dde)
2019-03-25 09:36:24.395580 | w |
2019-03-25 09:36:24.395713 | w |   Thread T12 (tid=930, running) created by main thread at:
2019-03-25 09:36:24.395831 | w |     #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
2019-03-25 09:36:24.396049 | w |     #1 cm_start /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:2028 (libsysrepo.so.0.7+0xb3c3d)
2019-03-25 09:36:24.396307 | w |     #2 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:110 (libsysrepo.so.0.7+0x23bf78)
2019-03-25 09:36:24.396537 | w |     #3 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
2019-03-25 09:36:24.396789 | w |     #4 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
2019-03-25 09:36:24.397243 | w |     #5 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.397842 | w |     #6 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.398276 | w |     #7 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.398430 | w |     #8 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.398771 | w |     #9 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.399035 | w |     #10 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.399263 | w |     #11 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
2019-03-25 09:36:24.399473 | w |     #12 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.399707 | w |     #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.400138 | w |     #14 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
2019-03-25 09:36:24.400374 | w |     #15 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
2019-03-25 09:36:24.400638 | w |     #16 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.400856 | w |     #17 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.401047 | w |     #18 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
2019-03-25 09:36:24.401208 | w |     #19 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.401383 | w |     #20 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.401419 | w |
2019-03-25 09:36:24.401527 | w |   Thread T8 (tid=926, running) created by main thread at:
2019-03-25 09:36:24.401644 | w |     #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
2019-03-25 09:36:24.401885 | w |     #1 rp_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:4008 (libsysrepo.so.0.7+0xd65c2)
2019-03-25 09:36:24.402106 | w |     #2 cm_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1957 (libsysrepo.so.0.7+0xb07aa)
2019-03-25 09:36:24.402388 | w |     #3 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:106 (libsysrepo.so.0.7+0x23be30)
2019-03-25 09:36:24.402622 | w |     #4 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
2019-03-25 09:36:24.402886 | w |     #5 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
2019-03-25 09:36:24.403331 | w |     #6 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.403923 | w |     #7 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.404345 | w |     #8 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.404498 | w |     #9 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.404838 | w |     #10 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.405101 | w |     #11 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.405329 | w |     #12 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
2019-03-25 09:36:24.405539 | w |     #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.405775 | w |     #14 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.406208 | w |     #15 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
2019-03-25 09:36:24.406443 | w |     #16 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
2019-03-25 09:36:24.406730 | w |     #17 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.406925 | w |     #18 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.407107 | w |     #19 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
2019-03-25 09:36:24.407281 | w |     #20 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.407443 | w |     #21 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.407477 | w |
2019-03-25 09:36:24.407586 | w |   Thread T11 (tid=929, running) created by main thread at:
2019-03-25 09:36:24.407726 | w |     #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
2019-03-25 09:36:24.407944 | w |     #1 rp_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:4008 (libsysrepo.so.0.7+0xd65c2)
2019-03-25 09:36:24.408168 | w |     #2 cm_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1957 (libsysrepo.so.0.7+0xb07aa)
2019-03-25 09:36:24.408426 | w |     #3 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:106 (libsysrepo.so.0.7+0x23be30)
2019-03-25 09:36:24.408664 | w |     #4 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
2019-03-25 09:36:24.408938 | w |     #5 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
2019-03-25 09:36:24.409128 | w |     #6 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.409389 | w |     #7 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.409577 | w |     #8 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.409645 | w |     #9 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.409799 | w |     #10 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.409916 | w |     #11 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
2019-03-25 09:36:24.410012 | w |     #12 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
2019-03-25 09:36:24.410105 | w |     #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.410199 | w |     #14 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
2019-03-25 09:36:24.410394 | w |     #15 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
2019-03-25 09:36:24.410492 | w |     #16 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
2019-03-25 09:36:24.410609 | w |     #17 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.410706 | w |     #18 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
2019-03-25 09:36:24.410789 | w |     #19 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
2019-03-25 09:36:24.410860 | w |     #20 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.410931 | w |     #21 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)
2019-03-25 09:36:24.410950 | w |
2019-03-25 09:36:24.411052 | w | SUMMARY: ThreadSanitizer: data race /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:595 in sr_msg_free
```
And shortly afterwards:
```
WARNING: ThreadSanitizer: data race (pid=917)
  Write of size 8 at 0x7b4400040010 by thread T12:
    #0 memcpy ??:? (test_sysrepo-notifications+0x485576)
    #1 sr__msg__init /home/ci/build/sysrepo/src/common/sysrepo.pb-c.c:4199 (libsysrepo.so.0.7+0x3c16c)
    #2 protobuf_c_message_unpack ??:? (libprotobuf-c.so.1+0x4b9a)
    #3 cm_conn_msg_process /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1015 (libsysrepo.so.0.7+0xba93d)
    #4 cm_conn_in_buff_process /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1133 (libsysrepo.so.0.7+0xb9578)
    #5 cm_conn_read_cb /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1215 (libsysrepo.so.0.7+0xb76ae)
    #6 ev_invoke_pending ??:? (libev.so.4+0x4f72)
    #7 cm_event_loop_threaded /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1891 (libsysrepo.so.0.7+0xb41cb)

  Previous read of size 8 at 0x7b4400040010 by thread T8:
    #0 sr_msg_free /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:592 (libsysrepo.so.0.7+0x99889)
    #1 rp_msg_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3687 (libsysrepo.so.0.7+0xdec92)
    #2 rp_worker_thread_execute /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3769 (libsysrepo.so.0.7+0xd7dde)

  Location is heap block of size 264 at 0x7b440003ffc0 allocated by thread T11:
    #0 malloc ??:? (test_sysrepo-notifications+0x4973e3)
    #1 sr_mem_new /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/common/sr_mem_mgmt.c:162 (libsysrepo.so.0.7+0x95624)
    #2 rp_subscribe_req_process /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:1832 (libsysrepo.so.0.7+0xfd0e8)
    #3 rp_req_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3502 (libsysrepo.so.0.7+0xe043f)
    #4 rp_msg_dispatch /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3668 (libsysrepo.so.0.7+0xde8fe)
    #5 rp_worker_thread_execute /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:3769 (libsysrepo.so.0.7+0xd7dde)

  Thread T12 (tid=930, running) created by main thread at:
    #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
    #1 cm_start /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:2028 (libsysrepo.so.0.7+0xb3c3d)
    #2 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:110 (libsysrepo.so.0.7+0x23bf78)
    #3 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
    #4 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
    #5 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
    #6 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
    #7 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
    #8 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
    #9 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
    #10 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
    #11 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
    #12 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
    #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
    #14 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
    #15 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
    #16 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
    #17 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
    #18 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
    #19 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
    #20 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)

  Thread T8 (tid=926, running) created by main thread at:
    #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
    #1 rp_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:4008 (libsysrepo.so.0.7+0xd65c2)
    #2 cm_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1957 (libsysrepo.so.0.7+0xb07aa)
    #3 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:106 (libsysrepo.so.0.7+0x23be30)
    #4 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
    #5 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
    #6 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
    #7 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
    #8 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
    #9 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
    #10 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
    #11 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
    #12 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
    #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
    #14 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
    #15 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
    #16 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
    #17 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
    #18 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
    #19 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
    #20 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
    #21 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)

  Thread T11 (tid=929, running) created by main thread at:
    #0 pthread_create ??:? (test_sysrepo-notifications+0x483bfa)
    #1 rp_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/request_processor.c:4008 (libsysrepo.so.0.7+0xd65c2)
    #2 cm_init /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/connection_manager.c:1957 (libsysrepo.so.0.7+0xb07aa)
    #3 cl_engine_init_local /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:106 (libsysrepo.so.0.7+0x23be30)
    #4 sr_connect /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/src/clientlib/client_library.c:426 (libsysrepo.so.0.7+0x23b405)
    #5 Connection /home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sysrepo/swig/cpp/src/Connection.cpp:41 (libSysrepo-cpp.so.0.7+0x16729)
    #6 std::__1::__compressed_pair_elem<sysrepo::Connection, 1, false>::__compressed_pair_elem<char const (&) [19], 0ul>(std::__1::piecewise_construct_t, std::__1::tuple<char const (&) [19]>, std::__1::__tuple_indices<0ul>) /usr/bin/../include/c++/v1/memory:2139 (test_sysrepo-notifications+0x5195ef)
    #7 std::__1::__compressed_pair<std::__1::allocator<sysrepo::Connection>, sysrepo::Connection>::__compressed_pair<std::__1::allocator<sysrepo::Connection>&, char const (&) [19]>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<sysrepo::Connection>&>, std::__1::tuple<char const (&) [19]>) /usr/bin/../include/c++/v1/memory:2241 (test_sysrepo-notifications+0x5195ef)
    #8 std::__1::__shared_ptr_emplace<sysrepo::Connection, std::__1::allocator<sysrepo::Connection> >::__shared_ptr_emplace<char const (&) [19]>(std::__1::allocator<sysrepo::Connection>, char const (&) [19]) /usr/bin/../include/c++/v1/memory:3654 (test_sysrepo-notifications+0x5195ef)
    #9 <null> /usr/bin/../include/c++/v1/memory:4313 (test_sysrepo-notifications+0x5195ef)
    #10 _ZNSt3__111make_sharedIN7sysrepo10ConnectionEJRA19_KcEEENS_9enable_ifIXntsr8is_arrayIT_EE5valueENS_10shared_ptrIS7_EEE4typeEDpOT0_ /usr/bin/../include/c++/v1/memory:4692 (test_sysrepo-notifications+0x5195ef)
    #11 ____C_A_T_C_H____T_E_S_T____0() /home/ci/src/cesnet-gerrit-czechlight/CzechLight/cla-sysrepo/tests/sysrepo-notifications.cpp:30 (test_sysrepo-notifications+0x5195ef)
    #12 Catch::TestInvokerAsFunction::invoke() const /home/ci/target/include/catch2/catch.hpp:11846 (test_sysrepo-notifications+0x5afb89)
    #13 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:11747 (test_sysrepo-notifications+0x5a5d89)
    #14 Catch::RunContext::invokeActiveTestCase() /home/ci/target/include/catch2/catch.hpp:10606 (test_sysrepo-notifications+0x5a5d89)
    #15 Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/ci/target/include/catch2/catch.hpp:10579 (test_sysrepo-notifications+0x5a3422)
    #16 Catch::RunContext::runTest(Catch::TestCase const&) /home/ci/target/include/catch2/catch.hpp:10349 (test_sysrepo-notifications+0x5a253f)
    #17 Catch::(anonymous namespace)::runTests(std::__1::shared_ptr<Catch::Config> const&) /home/ci/target/include/catch2/catch.hpp:10908 (test_sysrepo-notifications+0x5a9e9e)
    #18 Catch::Session::runInternal() /home/ci/target/include/catch2/catch.hpp:11103 (test_sysrepo-notifications+0x5a9e9e)
    #19 Catch::Session::run() /home/ci/target/include/catch2/catch.hpp:11060 (test_sysrepo-notifications+0x5a91ad)
    #20 main /home/ci/target/include/catch2/catch.hpp:10806 (test_sysrepo-notifications+0x5c565e)
    #21 main /home/ci/target/include/catch2/catch.hpp:14559 (test_sysrepo-notifications+0x5c565e)

SUMMARY: ThreadSanitizer: data race ??:? in memcpy
```

I'm afraid I do not understand sysrepo's internals well enough to be able to immediately tell whether it's a real problem, but it looks almost like a double-free to me.

This build is with sysrepo's default settings of memory management, i.e., `-DUSE_SR_MEM_MGMT:BOOL=ON`.

**Comment by michalvasko** [comment]
Hi,
you can try again with the latest `devel`.

Regards,
Michal

**Comment by jktjkt** [comment]
Thank you, I can no longer see this error. I also fixed some missing locking in my client code, but I don't think it is relevant.

If you're interested, [here are the remaining issues from the test run of libyang, sysrepo, libnetconf2 and netopeer](https://ci-logs.gerrit.cesnet.cz/t/public/logs//06/1606/1/check/f29-clang-tsan/0ba14d5/).

**Comment by michalvasko** [comment]
Hi,
I know I have not fixed all those problems, but I am working on other things so I put that on hold. I may take a look again later.

Regards,
Michal
