### ISSUE TITLE
[New sysrepo] weird behavior after install the same module for several times

### ISSUE THREAD

**Issue by brchiu** [sysrepo/sysrepo#1621]
Install the same yang modules for several times, failed to connect afterward.

It can not be recovered unless I clean up sysrepo by `sudo make sr_clean` again but it makes no sense.

```
~/sysrepo/build$ sudo make sr_clean
Built target sr_clean
~/sysrepo/build$ cd ../../RU-Yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
libyang[0]: Duplicated instance of "module" list. (path: /sysrepo:sysrepo-modules/module[name='ietf-yang-types'])
sysrepoctl error: Failed to connect (libyang error)
~/RU-YangRU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
libyang[0]: Duplicated instance of "module" list. (path: /sysrepo:sysrepo-modules/module[name='ietf-yang-types'])
sysrepoctl error: Failed to connect (libyang error)
~/RU-Yang$ sudo sysrepoctl -l
libyang[0]: Duplicated instance of "module" list. (path: /sysrepo:sysrepo-modules/module[name='ietf-yang-types'])
sysrepoctl error: Failed to connect (libyang error)

```

**Comment by brchiu** [comment]
I am not sure whether it is of the same cause, however, the steps to reproduce it is a little bit similar.

After I try to install an existing module, i.e. ietf-inet-types, after it displays `[ERR]: Module "ietf-interfaces" not scheduled for deletion. ....`, I am not able to connect to sysrepo anymore.

```
$ sudo sysrepoctl -l
Sysrepo repository: /media/brchiu/79918428768101F8/DocCollect/Project/sysrepo/build/repository

Module Name                | Revision   | Flags | Owner         | Permissions | Submodules | Features
-----------------------------------------------------------------------------------------------------
iana-hardware              | 2018-03-13 | i     |               |             |            |         
ietf-hardware              | 2018-03-13 | I     | brchiu:brchiu | 777         |            |         
ietf-inet-types            | 2013-07-15 | I     | brchiu:brchiu | 777         |            |         
ietf-interfaces            | 2018-02-20 | I     | brchiu:brchiu | 777         |            |         
ietf-ip                    | 2018-02-22 | I     | brchiu:brchiu | 777         |            |         
ietf-netconf               | 2011-06-01 | I     | brchiu:brchiu | 777         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | brchiu:brchiu | 777         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | brchiu:brchiu | 777         |            |         
ietf-yang-library          | 2019-01-04 | I     | brchiu:brchiu | 777         |            |         
yang                       | 2017-02-20 | I     | brchiu:brchiu | 777         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; X - Removed/U - Updated; F - Feature changes

~/RU-Yang$ sudo sysrepoctl -i ietf-interfaces.yang -v2
[ERR]: Module "ietf-interfaces" not scheduled for deletion.
[ERR]: Module "ietf-interfaces" is already in sysrepo.
~/RU-Yang$ sudo sysrepoctl -i ietf-hardware.yang -v2
[ERR]: Module "ietf-hardware" not scheduled for deletion.
[ERR]: Module "ietf-hardware" is already in sysrepo.
~/RU-Yang$ sudo sysrepoctl -l
sysrepoctl error: Failed to list modules (Item not found)
````

**Comment by michalvasko** [comment]
Hi,
please update *libyang* and *sysrepo*, internal modules were handled somewhat chaotically, so that should be fixed. Try it all again now, please. Anyway, good catch although there is no point in implementing non-implemented internal modules in practice.

Regards,
Michal

**Comment by brchiu** [comment]
After update to newest libyang, the second part seems to be solved, but the first one seems still exist.

```
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
~/RU-Yang$ sudo sysrepoctl -i ietf-yang-types.yang
libyang[0]: Duplicated instance of "module" list. (path: /sysrepo:sysrepo-modules/module[name='ietf-yang-types'])
sysrepoctl error: Failed to connect (libyang error)
~/RU-Yang$ sudo sysrepoctl -l
libyang[0]: Duplicated instance of "module" list. (path: /sysrepo:sysrepo-modules/module[name='ietf-yang-types'])
sysrepoctl error: Failed to connect (libyang error)
```

**Comment by brchiu** [comment]
hi, @michalvasko , I tried to install `ietf-yang-types.yang` because some modules, e.g. `ietf-hardware.yang` and `o-ran-interfaces.yang` import it. As you said, it is an "non-implemented internal modules", does it mean that I do not need to install it and can use `ietf-hardware` and `o-ran-interfaces` normally ? 
By the way, how I distinguish between modules have to be implemented and/or not necessary implemented but can be used normally ?

thanks very much.
regards
brchiu.

**Comment by michalvasko** [comment]
Hi,
have you updated *sysrepo* as well? I said you need to update both. I am not able to reproduce it anymore.

As for your other question, you do not have to concern yourself with this at all, it is up to *libyang* (and it can be extremely difficult to get it right, I may add) to load all import modules and implement those that are needed. *sysrepo* does not duplicate this functionality, so you must install only **modules whose data you actually want to instantiate** (configure). If there are modules that need to be implemented for some other module to be installed, the dependency module is automatically installed as well (you can see this in *sysrepoctl* if you use `-v3`). Import modules are of no concern at all, *sysrepo* simply copies them to its local YANG directory so that *libyang* can always find them.

Regards,
Michal

**Comment by brchiu** [comment]
hi @michalvasko, I did not update `sysrepo`, my bad, now it works. Many thanks !
