### ISSUE TITLE
How to encrypt and store passwords

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1785]
Hi Michal,

Could you please help me with some example for the implementation for storing encrypted passwords.

I thought of using SR_EV_UPDATE but its throwing internal error when updating already existing node.
Other than EV_UPDATE, could you please suggest any better approach.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I have just pushed a change that should prohibit invalid update subscriptions so you should not get any internal errors no matter what you subcsribe to. Can you please pull, try it again and in case you see the internal error, tell me how to reproduce it? Thanks.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Still getting internal error.
UPDATE subscription is successful earlier also. 
Scenario as below.

1. UPDATE subscription
2. CHANGE subscription
2.1. In update event set password using `sr_set_item_str` with encrypted value. (password field with user given password is already present in diff)
3. In change event get all data. 
3.1 This get data fails with Internal error.

For checking it I have changed UT(test_apply_changes) exception came if I changed `eth52/type` to `l3ipvlan` in update event. Where it passed if I add/set any new nodes.

**UT patch**
```
diff --git a/tests/test_apply_changes.c b/tests/test_apply_changes.c
index 714f9ba..2212e51 100644
--- a/tests/test_apply_changes.c
+++ b/tests/test_apply_changes.c
@@ -619,6 +619,8 @@ module_update_cb(sr_session_ctx_t *session, const char *module_name, const char
         sr_free_change_iter(iter);
 
         /* let's create another interface */
+        ret = sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='eth52']/type",
+                "iana-if-type:l3ipvlan", NULL, 0);
         ret = sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='eth64']/type",
                 "iana-if-type:ethernetCsmacd", NULL, 0);
         assert_int_equal(ret, SR_ERR_OK);
```
**UT result**
```
$ make test
Running tests...
Test project /opt/samba/skandukuri/sriram/new/sysrepo/build
      Start  1: test_modules
 1/22 Test  #1: test_modules .....................   Passed    0.79 sec
      Start  2: test_validation
 2/22 Test  #2: test_validation ..................   Passed    0.04 sec
      Start  3: test_edit
 3/22 Test  #3: test_edit ........................   Passed    0.07 sec
      Start  4: test_candidate
 4/22 Test  #4: test_candidate ...................   Passed    0.07 sec
      Start  5: test_operational
 5/22 Test  #5: test_operational .................   Passed    0.16 sec
      Start  6: test_lock
 6/22 Test  #6: test_lock ........................   Passed    2.09 sec
      Start  7: test_apply_changes
 7/22 Test  #7: test_apply_changes ...............***Exception: Other  0.12 sec
      Start  8: test_copy_config
 8/22 Test  #8: test_copy_config .................***Exception: Other  0.00 sec
      Start  9: test_rpc_action
 9/22 Test  #9: test_rpc_action ..................***Exception: Other  0.00 sec
      Start 10: test_notif
10/22 Test #10: test_notif .......................***Exception: Other  0.00 sec
      Start 11: test_get
11/22 Test #11: test_get .........................***Exception: Other  0.00 sec
      Start 12: test_modules_valgrind
12/22 Test #12: test_modules_valgrind ............***Exception: Other  4.86 sec
      Start 13: test_validation_valgrind
13/22 Test #13: test_validation_valgrind .........***Exception: Other  0.47 sec
      Start 14: test_edit_valgrind
14/22 Test #14: test_edit_valgrind ...............***Exception: Other  0.47 sec
      Start 15: test_candidate_valgrind
15/22 Test #15: test_candidate_valgrind ..........***Exception: Other  0.47 sec
      Start 16: test_operational_valgrind
16/22 Test #16: test_operational_valgrind ........***Exception: Other  0.47 sec
      Start 17: test_lock_valgrind
17/22 Test #17: test_lock_valgrind ...............***Exception: Other  0.47 sec
      Start 18: test_apply_changes_valgrind
18/22 Test #18: test_apply_changes_valgrind ......***Exception: Other  0.47 sec
      Start 19: test_copy_config_valgrind
19/22 Test #19: test_copy_config_valgrind ........***Exception: Other  0.47 sec
      Start 20: test_rpc_action_valgrind
20/22 Test #20: test_rpc_action_valgrind .........***Exception: Other  0.47 sec
      Start 21: test_notif_valgrind
21/22 Test #21: test_notif_valgrind ..............***Exception: Other  0.47 sec
      Start 22: test_get_valgrind
22/22 Test #22: test_get_valgrind ................***Exception: Other  0.47 sec
```

Looks like updating some existing value in UPDATE event is not working.

Please correct me if I am wrong.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
firstly, your change of `test_apply_changes` is wrong. You have changed the data so you should have also changed the XML where these data are being compared and checked, the test would pass then.

However, when I added getting the data on `SR_EV_CHANGE` event, I reproduced the problem. Actually, I am surprised the existing test was passing because there was quite a major issue with merging the changes from the updated event, but it should be fixed and changing an existing value is working in the test.

Regards,
Michal
