### ISSUE TITLE
rpc output contains decimal64 data setting failed

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1880]
Hi:
I have a problem, the output of rpc contains decimal64 data setting failed,
(1)I don't know how to set the value of decimal64 in output.
```code
    (*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
    (*output)[1].type = SR_DECIMAL64_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.decimal64_val = 2.3;
```
(2)I don't know if there is any parsing of such data in sysrepo or libyang.

Here is the process I tested:

Here are 2 yang modules:
---rpc-test-type.yang
```yang
module rpc-test-type {
  namespace "urn:rpc-test-type";
  prefix rpc-test-type;

  typedef real {
        type union {
            type decimal64 {
                fraction-digits 2;
            }
            type decimal64 {
                fraction-digits 18;
            }
        }
    }
}
```
---rpc-test-module.yang
```yang
module rpc-test-module {
    yang-version 1.1;
	namespace "urn:rpc-test-module";
    prefix rpc-test-module;
	
	import rpc-test-type {
        prefix rpc-test-type;
    }
	
	grouping test-outputs {
        list test-output {
            key 'output-name output-type';
            leaf output-name {
                type string {
                    length "1..64";
                }
            }
            leaf output-type {
                type string {
                    length "1..64";
                }
            }
            container a {
                leaf a1-value {
                    type rpc-test-type:real;
                }
                leaf a2-value {
                    type rpc-test-type:real;
                }
            }
        }
    }
	
	rpc get-rpc-data {
            input {
                leaf name {
                    type string {
                        length "1..64";
                    }
                    description "none";
                }
                leaf type {
                    mandatory true;
                    type string {
                        length "1..64";
                    }
                    description "none";
                }
            }
            output {
		    leaf id {
                    type string {
                        length "1..64";
                    }
                    description "none";
                }
                container test-outputs {
                    uses test-outputs;
                    description "none";
                } 
            }
    }
	
}
```

1. install module
    sysrepoctl -i rpc-test-type.yang
    sysrepoctl  -i rpc-test-module.yang

2. netopeer2-cli:
     user-rpc --content rpc-test-module.xml
---rpc-test-module.xml:
```xml
<get-rpc-data xmlns="urn:rpc-test-module">
	<name>test-name</name>
	<type>test-type</type>
</get-rpc-data>
```

3. Start subscribing to rpc(rpc_test_module_list.c)
    
[rpc_test_module_list.txt](https://github.com/sysrepo/sysrepo/files/4408632/rpc_test_module_list.txt)

```code
     rc = sr_rpc_subscribe(session, "/rpc-test-module:get-rpc-data", rpc_cb_get_rpc_data, NULL, 0, 0, &subscription);
```
```code
static int
rpc_cb_get_rpc_data(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
    for (i = 0; i < input_cnt; ++i) {
        print_val(&input[i]);
    }

    if (!strcmp(path, "/rpc-test-module:get-rpc-data")) {
        /* generate some output */
        *output_cnt = 2;
        *output = calloc(2, sizeof **output);

    (*output)[0].xpath = strdup("/rpc-test-module:get-rpc-data/id");
    (*output)[0].type = SR_STRING_T;
    (*output)[0].dflt = 0;
    (*output)[0].data.string_val = strdup("1");

    /*Set failed*/
    (*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
    (*output)[1].type = SR_DECIMAL64_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.decimal64_val = 2.3;

    }
    return SR_ERR_OK;
}
```
**rpc_test_module_list.c log:**
```code
[ERR]: Schema node not found. (path: /rpc-test-module:get-rpc-data/test-outputs)
[ERR]: Invalid value "" in "a1-value" element. (path: /rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value)
[ERR]: Failed to create node "a1-value" as a child of "a". (path: /rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value)
Error in `./rpc_test_module_list': free(): invalid size: 0x00007f95600008f0
```

**netopeer2-server log:**
```code
[WRN]: SR: Cleaning up after a non-existent sysrepo client with PID 3207.
netopeer2-server: /home/linux/cxt_netconf/sysrepo-devel/src/shm_main.c:388: sr_shmmain_ext_print: Assertion `*((size_t *)ext_shm_addr) == wasted' failed.
```

I hope to be able to successfully send RPC data (xpath="/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value"), thanks!

thanks

**Comment by xxyy0906** [comment]
Hi,
Sorry, this is a problem with my code.

thanks!

**Comment by xxyy0906** [comment]
Hi,
I'm very sorry, even if I modify my code, the problem still exists, but I'm sure it's not the problem of the list node in the output, but the problem of the leaf node in the container node in the list node, so I reopened it.

thanks!

**Comment by xxyy0906** [comment]
Hi,
I am very sorry, this time I am sure that the decimal64 type has affected the filling of the output data. I searched for the case code, but I did not find the result. So I reopened it. 

thanks!

**Comment by michalvasko** [comment]
Hi,
sure enough, there was a problem that manifested only for `decimal64` type. Should work now.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
I think this modification is effective, but the output of rpc on netopeer2-cli does not seem to get the desired result(Accuracy problem).
example1:
```code
(*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
    (*output)[1].type = SR_DECIMAL64_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.decimal64_val = 10.0000000000000001;
```
netopeer2-cli:
```code
<id xmlns="urn:rpc-test-module">1</id>
<test-outputs xmlns="urn:rpc-test-module">
  <test-output>
    <output-name>test-output-name</output-name>
    <output-type>test-output-type</output-type>
    <a>
      <a1-value>10.0</a1-value>
    </a>
  </test-output>
</test-outputs>
```
example2:
```code
(*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
    (*output)[1].type = SR_DECIMAL64_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.decimal64_val = 2.01;
```
netopeer2-cli:
```code
<id xmlns="urn:rpc-test-module">1</id>
<test-outputs xmlns="urn:rpc-test-module">
  <test-output>
    <output-name>test-output-name</output-name>
    <output-type>test-output-type</output-type>
    <a>
      <a1-value>2.0</a1-value>
    </a>
  </test-output>
</test-outputs>
```

**Comment by xxyy0906** [comment]
Hi,
Sorry, i still can't get the value on the cli.
```code
rc = sr_rpc_subscribe_tree(session, "/rpc-test-module:get-rpc-data", rpc_cb_get_rpc_data, NULL, 0, 0, &subscription);
```
```code
static int
rpc_cb_get_rpc_data(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);

    if (!strcmp(path, "/rpc-test-module:get-rpc-data")) {
        /* generate some output */
	struct lyd_node *node;
	node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
	lyd_new_path(node, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "2.23", 0, 0);
    }
    return SR_ERR_OK;
}
```

netopeer2-cli log:
user-rpc --content rpc-test-module.xml
OK
> 
I can't see the data now.

thanks!

**Comment by michalvasko** [comment]
Hi,
you managed to compile this? You must also change your callback prototype to match the tree function so this is completely wrong and I am surprised it did not crash.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
Sorry this is my negligence,But i have 2 questions.
1.I don't know how to recurse to give the value.(I looked up the sample code but couldn't find it)
example:
success:
```code
node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
node1 = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "2.23", 0, LYD_PATH_OPT_OUTPUT);
```
fail:
```code
node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
lyd_new_path(node, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "2.23", 0, 0);
```
2.When I use the following code still cannot get the expected value.
```code
rc = sr_rpc_subscribe_tree(session, "/rpc-test-module:get-rpc-data", rpc_action_cb, NULL, 0, 0, &subscription);
```
```code
static int
rpc_action_cb(sr_session_ctx_t *session, const char *xpath, const struct lyd_node *input, sr_event_t event,
        uint32_t request_id, struct lyd_node *output, void *private_data)
{
    struct lyd_node *node;
	struct lyd_node *node1;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    if (!strcmp(xpath, "/rpc-test-module:get-rpc-data")){
        /* create output data */
	node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
	node1 = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "10.0000000000000001", 0, LYD_PATH_OPT_OUTPUT);
    }
    return SR_ERR_OK;
}
```
netopeer2-cli log:
user-rpc --content rpc-test-module.xml
DATA
```xml
<id xmlns="urn:rpc-test-module">test-id</id>
```

I tried 10.0000000000000001 can be successful, but a cannot be successful.

thanks!

**Comment by xxyy0906** [comment]
Hi,
Sorry this is my negligence,And it ’s not detailed,But i have 1 questions.
1.I don't know how to recurse to give the value.(I looked up the sample code but couldn't find it)
example:
success:
```code
rc = sr_rpc_subscribe_tree(session, "/rpc-test-module:get-rpc-data", rpc_action_cb, NULL, 0, 0, &subscription);
```
```code
static int
rpc_action_cb(sr_session_ctx_t *session, const char *xpath, const struct lyd_node *input, sr_event_t event,
        uint32_t request_id, struct lyd_node *output, void *private_data)
{
    struct lyd_node *node;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    if (!strcmp(xpath, "/rpc-test-module:get-rpc-data")){
        /* create output data */
	node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
	 lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "9.223372036854775807", 0, LYD_PATH_OPT_OUTPUT);
    }
    return SR_ERR_OK;
}
```
fail:
```code
node = lyd_new_path(output, NULL, "/rpc-test-module:get-rpc-data/id", "test-id", 0, LYD_PATH_OPT_OUTPUT);
lyd_new_path(node, NULL, "/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value", "2.23", 0, 0);
```

In fact, the (success) code above did what I expected.This question is also not important.

thanks!

**Comment by lin13051275755** [comment]
> Hi:
> I have a problem, the output of rpc contains decimal64 data setting failed,
> (1)I don't know how to set the value of decimal64 in output.
> 
> ```
>     (*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
>     (*output)[1].type = SR_DECIMAL64_T;
>     (*output)[1].dflt = 0;
>     (*output)[1].data.decimal64_val = 2.3;
> ```
> 
> (2)I don't know if there is any parsing of such data in sysrepo or libyang.
> 
> Here is the process I tested:
> 
> Here are 2 yang modules:
> ---rpc-test-type.yang
> 
> ```yang
> module rpc-test-type {
>   namespace "urn:rpc-test-type";
>   prefix rpc-test-type;
> 
>   typedef real {
>         type union {
>             type decimal64 {
>                 fraction-digits 2;
>             }
>             type decimal64 {
>                 fraction-digits 18;
>             }
>         }
>     }
> }
> ```
> 
> ---rpc-test-module.yang
> 
> ```yang
> module rpc-test-module {
>     yang-version 1.1;
> 	namespace "urn:rpc-test-module";
>     prefix rpc-test-module;
> 	
> 	import rpc-test-type {
>         prefix rpc-test-type;
>     }
> 	
> 	grouping test-outputs {
>         list test-output {
>             key 'output-name output-type';
>             leaf output-name {
>                 type string {
>                     length "1..64";
>                 }
>             }
>             leaf output-type {
>                 type string {
>                     length "1..64";
>                 }
>             }
>             container a {
>                 leaf a1-value {
>                     type rpc-test-type:real;
>                 }
>                 leaf a2-value {
>                     type rpc-test-type:real;
>                 }
>             }
>         }
>     }
> 	
> 	rpc get-rpc-data {
>             input {
>                 leaf name {
>                     type string {
>                         length "1..64";
>                     }
>                     description "none";
>                 }
>                 leaf type {
>                     mandatory true;
>                     type string {
>                         length "1..64";
>                     }
>                     description "none";
>                 }
>             }
>             output {
> 		    leaf id {
>                     type string {
>                         length "1..64";
>                     }
>                     description "none";
>                 }
>                 container test-outputs {
>                     uses test-outputs;
>                     description "none";
>                 } 
>             }
>     }
> 	
> }
> ```
> 
> 1. install module
>    sysrepoctl -i rpc-test-type.yang
>    sysrepoctl  -i rpc-test-module.yang
> 2. netopeer2-cli:
>    user-rpc --content rpc-test-module.xml
>    ---rpc-test-module.xml:
> 
> ```
> <get-rpc-data xmlns="urn:rpc-test-module">
> 	<name>test-name</name>
> 	<type>test-type</type>
> </get-rpc-data>
> ```
> 
> 1. Start subscribing to rpc(rpc_test_module_list.c)
> 
> [rpc_test_module_list.txt](https://github.com/sysrepo/sysrepo/files/4408632/rpc_test_module_list.txt)
> 
> ```
>      rc = sr_rpc_subscribe(session, "/rpc-test-module:get-rpc-data", rpc_cb_get_rpc_data, NULL, 0, 0, &subscription);
> ```
> 
> ```
> static int
> rpc_cb_get_rpc_data(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
>         sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
> {
>     size_t i;
> 
>     (void)session;
>     (void)event;
>     (void)request_id;
>     (void)private_data;
> 
>     printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
>     for (i = 0; i < input_cnt; ++i) {
>         print_val(&input[i]);
>     }
> 
>     if (!strcmp(path, "/rpc-test-module:get-rpc-data")) {
>         /* generate some output */
>         *output_cnt = 2;
>         *output = calloc(2, sizeof **output);
> 
>     (*output)[0].xpath = strdup("/rpc-test-module:get-rpc-data/id");
>     (*output)[0].type = SR_STRING_T;
>     (*output)[0].dflt = 0;
>     (*output)[0].data.string_val = strdup("1");
> 
>     /*Set failed*/
>     (*output)[1].xpath = strdup("/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value");
>     (*output)[1].type = SR_DECIMAL64_T;
>     (*output)[1].dflt = 0;
>     (*output)[1].data.decimal64_val = 2.3;
> 
>     }
>     return SR_ERR_OK;
> }
> ```
> 
> **rpc_test_module_list.c log:**
> 
> ```
> [ERR]: Schema node not found. (path: /rpc-test-module:get-rpc-data/test-outputs)
> [ERR]: Invalid value "" in "a1-value" element. (path: /rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value)
> [ERR]: Failed to create node "a1-value" as a child of "a". (path: /rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value)
> Error in `./rpc_test_module_list': free(): invalid size: 0x00007f95600008f0
> ```
> 
> **netopeer2-server log:**
> 
> ```
> [WRN]: SR: Cleaning up after a non-existent sysrepo client with PID 3207.
> netopeer2-server: /home/linux/cxt_netconf/sysrepo-devel/src/shm_main.c:388: sr_shmmain_ext_print: Assertion `*((size_t *)ext_shm_addr) == wasted' failed.
> ```
> 
> I hope to be able to successfully send RPC data (xpath="/rpc-test-module:get-rpc-data/test-outputs/test-output[output-name='test-output-name'][output-type='test-output-type']/a/a1-value"), thanks!
> 
> thanks

@xxyy0906 hi,I have the same problem,can you give me some idea

**Comment by xxyy0906** [comment]
Okay. You said

 
---Original---

**Comment by lin13051275755** [comment]
@xxyy0906 
same problem，get rpc output contains decimal64 data setting failed；Schema node not found；
![image](https://user-images.githubusercontent.com/50852871/95651892-e04d8300-0b1f-11eb-99cd-3b1132c57f7d.png)
find our model is same ；can make friends？my WeChat is 13051275755
