### ISSUE TITLE
Cannot access module back after one user callback failure

### ISSUE THREAD

**Issue by AeroFlorian** [sysrepo/sysrepo#2627]
Hi all,
After a user callback failure on a get request on a module, sysrepo does not answer anymore for this module.
The following scenario works on v1.4.122, but does not in v2.0.47, nor on devel branch.
Scenario:

1. set a failure on the user callback for module my-module
2. make a get request for module my-module with netopper2-cli (ERROR is expected, as the callback returns SR_ERR_CALLBACK_FAILED)
```
get --filter-xpath /my-module:my-module-root
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed
        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed
```

We have 2 responses, not sure this is normal, but ERROR is okay here.

3. remove the failure on the user callback for module my-module
4. make a get request for module my-module with netopeer2-cli (DATA is expected)
```
 get --filter-xpath /my-module:my-module-root
cli_send_recv: Timeout for receiving a reply expired.
```

From logs it seems sysrepo is stuck with previous event processing.
Following scenario:
For step 2 we have those logs:
```
2021-11-02 08:42:19,342 DEBG 'mysw' stdout output:
[INF]: 08:42:19: SR: Processing "my-module" "operational" event with ID 2.
[INF]: 08:42:19: OR: mysw/my-module.c:74  ========== DATA FOR "my-module" "/my-module:module-root" REQUESTED =======================
[INF]: 08:42:19: OR: mysw/my-module.c:77 Failure on get configured, sending an error.

2021-11-02 08:42:19,342 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: User callback failed
[WRN]: SR: Event "operational" with ID 2 failed (User callback failed).
[ERR]: SR: User callback failed.
[ERR]: NP: Getting data "/my-module:*" from sysrepo failed (User callback failed).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 2 priority 0 failed (User callback failed).

2021-11-02 08:42:19,342 DEBG 'orusw' stdout output:
[INF]: 08:42:19: SR: Failed processing of "operational" event with ID 2.

2021-11-02 08:42:19,342 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
```

That step is ok. (the last two logs seem to point out that two gets are being sent to sysrepo at the same time though).

Then, for step 4 we have:
```
2021-11-02 08:42:43,693 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/common.c:4125).
[ERR]: SR: Waiting for subscription of "my-module" failed, previous event "(null)" with ID 2 was not processed.
[ERR]: NP: Getting data "/my-module:*" from sysrepo failed (Timeout expired).

2021-11-02 08:42:43,693 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: Waiting for subscription of "my-module" failed, previous event "(null)" with ID 2 was not processed.
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (Timeout expired).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
```

Sysrepo answers for other modules but not anymore for my-module.

**Comment by michalvasko** [comment]
This was quite a straightforward use-case that was really not working since version 1.4.134. It was a regression because there was no test, surprisingly. So, now it should work in both latest `devel` (version 2.x) and `libyang1` (version 1.x). Thanks for the report.

**Comment by AeroFlorian** [comment]
It works on v2.0.47 taking the patch from your commit as well.
Thanks a lot!!!!

**Comment by guangjung** [comment]
Hi michalvasko, which  version 1.x fixed the question?   If not , How to fix the question in version 1.4.122 or 1.4.140?  Look forward to your reply， thanks.

**Comment by michalvasko** [comment]
The commits are referenced so you should be able to learn on your own what you are asking. It was fixed in the latest *libyang1* branch, v1.4.149.

**Comment by guangjung** [comment]
Hi michalvasko, the issue still persists in the latest libyang1 branch, v1.4.149.  
we used netopeer2 (latest libyang1 branch),  libyang (latest libyang1 branch),  libnetconf2 (latest libyang1 branch) and sysrepo (latest libyang1 branch).

Scenario: 
step1. By calling sr_get_data to get operational data under high pressure，the issue appears after about 2 hours.  

step2. continue to call sr_get_items_example, the error is printed as follows：

sh-4.3# sr_get_items_example "/openconfig-platform:components/component//*" operational
Application will get "/openconfig-platform:components/component//*" from "operational" datastore.

[ERR]: Internal error (/home/guangjung/install_sysrepo_20211202/sysrepo/src/common.c:3736).
[ERR]: Waiting for subscription of "openconfig-platform" failed, previous event "(null)" with ID 2014 was not processed.

step3.  Sysrepo answers for other modules but not anymore for openconfig-platform.

**Comment by michalvasko** [comment]
> the issue appears after about 2 hours.

That is an extreme corner case that is not worth fixing in v1. If you happen to reproduce this in v2, I would attempt to debug it further.

**Comment by guangjung** [comment]
Hi michalvasko, we made further test and attempt in v1.4.149,  and found only calling sr_get_data will reproduce the issue , but calling sr_get_items or sr_get_subtree could NOT reproduce this.   

We further narrow the scope， the issue is easy to  be reproduced in v1.4.149 or v1.4.122. 

step1.  Establish a long connection by netopeer2-cli.
./netopeer2-cli
connect --login admin --host  127.0.0.1 --port 830

step2.  Execute the following commands every 1s.

get --filter-xpath=/openconfig-platform:*

step3. after about 5 mins , the issue was reproduced

Can you take a look at this?  Thanks a lot.

**Comment by michalvasko** [comment]
Firstly, please provide the whole use-case, you have described only the steps taken of the client, what about the server? What subscriptions do you have?

After I manage to reproduce it I will try it for *sysrepo* v2 and if it works there, I will likely not waste time fixing it for v1.

**Comment by Krisscut** [comment]
Hi !

I'm seing similar traces in a run done with netopeer2-2.1.49 and sysrepo sysrepo-2.2.36.

We have a similar scenario as the one explained in the initial issue, with an initial failure during a get (expected):
(For context, we have 2 services subscribed to the _/o-ran-uplane-conf:user-plane-configuration_ path, orusw in C and OranManager in python. Orusw will return an error on the get callback the first time, but on the second attempt it should be fine)

```
2023-03-05 14:34:20,458 DEBG 'netopeer2-server' stdout output:
[DBG]: LN: Session 1: Received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="90"><get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><filter type="xpath" xmlns:o-ran-uplane-conf="urn:o-ran:uplane-conf:1.0" select="/o-ran-uplane-conf:user-plane-configuration"/></get></rpc>

2023-03-05 14:34:20,459 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 6 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).

2023-03-05 14:34:20,658 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Published event "operational get" "/o-ran-uplane-conf:user-plane-configuration" with ID 16.

2023-03-05 14:34:20,658 DEBG 'orusw' stderr output:
2023-03-05 14:34:20/INF:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, Processing "o-ran-uplane-conf" "operational get" event with ID 16.
2023-03-05 14:34:20/INF:UE_APP-OAM/orusw[RU01]: airphone-orusim/orusw/o-ran-uplane-conf.c:573  ========== DATA FOR "o-ran-uplane-conf" "/o-ran-uplane-conf:user-plane-configuration" REQUESTED (SUB ID = 129 REQ ID = 16) =======================
2023-03-05 14:34:20/INF:UE_APP-OAM/orusw[RU01]: airphone-orusim/orusw/o-ran-uplane-conf.c:576 Failure on get configured, sending an error.
2023-03-05 14:34:20/INF:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, Failed processing of "operational get" event with ID 16.

2023-03-05 14:34:20,658 DEBG 'oranManager' stdout output:
2023-03-05 14:34:20.658 INFO/UE_APP-OAM/OranManagerV2: OranManagerV2.py:85 - callbackUplaneConfGetOperational() - In get operational: 
2023-03-05 14:34:20.658 INFO/UE_APP-OAM/OranManagerV2: OranManagerV2.py:104 - callbackUplaneConfGetOperational() - Returning info for 1 rx_arrays and 1 tx_arrays

2023-03-05 14:34:20,659 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Published event "operational get" "/o-ran-uplane-conf:user-plane-configuration" with ID 16.

2023-03-05 14:34:20,660 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: User callback failed
[WRN]: SR: Event "operational" with ID 16 failed (User callback failed).

2023-03-05 14:34:20,660 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: User callback failed.
[ERR]: NP: Getting data "/o-ran-uplane-conf:user-plane-configuration" from sysrepo failed (User callback failed).
[INF]: SR: Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (User callback failed).

2023-03-05 14:34:20,661 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[DBG]: LN: Session 1: Sending message:

#490



2023-03-05 14:34:20,661 DEBG 'netopeer2-server' stdout output:
[DBG]: LN: Session 1: Sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="90"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">User callback failed</error-message></rpc-error><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">User callback failed.</error-message></rpc-error></rpc-reply>

```

Then we configure to not have any error with another rpc which is processed just fine, and we make another get request which fails with a similar error as the one described in the initial issue :

```
2023-03-05 14:34:20,768 DEBG 'netopeer2-server' stdout output:
[DBG]: LN: Session 1: Received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="92"><get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><filter type="xpath" xmlns:o-ran-uplane-conf="urn:o-ran:uplane-conf:1.0" select="/o-ran-uplane-conf:user-plane-configuration"/></get></rpc>
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 7 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 7 priority 0 (remaining 1 subscribers).


2023-03-05 14:34:30,871 DEBG 'netopeer2-server' stdout output:
[ERR]: SR: Internal error (/workspace/Services/3rdParty/sysrepo-2.2.36/src/common.c:5573).
[ERR]: SR: Waiting for subscription of "o-ran-uplane-conf" failed, previous event "(null)" with ID 16 was not processed.
[ERR]: NP: Getting data "/o-ran-uplane-conf:user-plane-configuration" from sysrepo failed (Timeout expired).

2023-03-05 14:34:30,872 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Failed processing of "rpc" event with ID 7 priority 0 (remaining 1 subscribers).
[ERR]: SR: Waiting for subscription of "o-ran-uplane-conf" failed, previous event "(null)" with ID 16 was not processed.
[WRN]: SR: Event "rpc" with ID 7 priority 0 failed (Timeout expired).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).

2023-03-05 14:34:30,872 DEBG 'netopeer2-server' stdout output:
[DBG]: LN: Session 1: Sending message:

#579

2023-03-05 14:34:30,872 DEBG 'netopeer2-server' stdout output:
[DBG]: LN: Session 1: Sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="92"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Waiting for subscription of "o-ran-uplane-conf" failed, previous event "(null)" with ID 16 was not processed.</error-message></rpc-error><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">User callback failed.</error-message></rpc-error></rpc-reply>
```

To have this behavior, the main difference is that we moved to use a new software based on sysrepo-python  (sysrepo-python-1.4.0) instead instead of a C based implementation.
Is it possible that the fix didn't cover the API used by sysrepo-python ? 
Maybe I should try to open an issue on sysrepo-python's repo as well, but since the behavior is really close to the initial one I think it is fitting to use this thread.

**Comment by michalvasko** [comment]
Based on the description I have no idea how to reproduce this, not to mention fix. Using Python bindings should not matter but I would really need to reproduce it to understand what is going on. You could also try using the latest `devel` branches of *netopeer2* and *sysrepo*. If nothing else, the *sysrepo* messages were improved.

**Comment by Krisscut** [comment]
After more digging, it looks like the issue is linked to the fact we have both applications registered on the same operational get callback path **/o-ran-uplane-conf:user-plane-configuration**. (We are using the MERGE mode)

If on the python application I split the callback in 2 **/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers** and **/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers**, there are no issues.

```
2023-03-06 10:25:46,530 DEBG 'orusw' stderr output:
2023-03-06 10:25:46/INF:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, Successful processing of "operational get" event with ID 17.

2023-03-06 10:25:46,530 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Event "operational get" with ID 17 succeeded.

2023-03-06 10:25:46,531 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Published event "operational get" "/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers" with ID 4.

2023-03-06 10:25:46,532 DEBG 'oranManager' stdout output:
2023-03-06 10:25:46.531 INFO/UE_APP-OAM/OranManagerV2: OranManagerV2.py:124 - callbackUplaneConfGetOperationalTx() - Returning info for 1 tx_arrays

2023-03-06 10:25:46,533 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Event "operational get" with ID 4 succeeded.

2023-03-06 10:25:46,533 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Published event "operational get" "/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers" with ID 4.

2023-03-06 10:25:46,534 DEBG 'oranManager' stdout output:
2023-03-06 10:25:46.533 INFO/UE_APP-OAM/OranManagerV2: OranManagerV2.py:103 - callbackUplaneConfGetOperationalRx() - Returning info for 1 rx_arrays

2023-03-06 10:25:46,534 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Event "operational get" with ID 4 succeeded.

2023-03-06 10:25:46,536 DEBG 'netopeer2-server' stdout output:
[INF]: SR: Successful processing of "rpc" event with ID 7 priority 0 (remaining 0 subscribers).
```

So it looks like the problem is when we have 2 applications with the same path and one of them fail.
In the previous trace, I noticed there are 2 publish with the same ID but if I trust the timestamp no action is triggered on the second one.
![image](https://user-images.githubusercontent.com/8125922/223089148-c7367619-97f4-46ed-bef6-c399aa955ba4.png)

**Comment by Krisscut** [comment]
1. We have 2 subscriptions on a single XPath **/o-ran-uplane-conf:user-plane-configuration**.
2. First get is done, both call returns OK --> no Error.
3. First application is configured to return an error in the get-callback through an edit-config --> ok
4. Get is done on the xpath **/o-ran-uplane-conf:user-plane-configuration**, first callback returns an error while second one returns OK --> Error is reported as expected.
5. First application is configured to not return anymore in the get-callback through an edit-config -> ok
6. Get is done again on the xpath **/o-ran-uplane-conf:user-plane-configuration**, this time the callbacks are not called anymore, and we timeout with the error messages provided previously.



> Can you mention the use-case exactly, please? Specifically, you have 2 subscriptions on a single XPath and the first or second (which?) fails? There is a test in _sysrepo_ with 5 subscriptions and the 3rd failing.
> 
> Also, the IDs are fine, each subscription has its own ID counter. If you use _sysrepo_ `devel`, the subscription index will be included in the message as well to avoid any confusion.

In this test with 5 subscriptions and the 3rd is failing, do you check that you are able to make another request after it failed  ?
And do you have multiple subscriptions on the same XPATH from 2 applications ?

**Comment by michalvasko** [comment]
In the scenario description, you are talking about "first application" but never about a second, so are there 2 or only one? Also, what exactly is
```
First application is configured to not return anymore in the get-callback through an edit-config -> ok
```
supposed to mean? If a callback is never processed, the event gets stuck, which is exactly what is happening in your case. Please include more details in the description because I do not understand it at all currently.

> Since it work after the split of the callback, we were wondering if the issue is because we have 2 callback on the same path, and since the first one failed it returns early without processing the answer from the second one.

That should not happen, the test checks for that, for example.

**Comment by Krisscut** [comment]
Yes we do have 2 applications, "orusw" and "oranManager" as seen in the logs previously.
First application is "orusw" and the second one is "OranManager". The OranManager always return an answer with a content when requested. It is the orusw that can be configured to return an error in our scenario.

> supposed to mean? If a callback is never processed, the event gets stuck, which is exactly what is happening in your case. Please include more details in the description because I do not understand it at all currently.

yes sorry my bad I forgot part of the sentence., I meant it is configured to **not return** an error anymore in the get-callback.

In the traces included here https://github.com/sysrepo/sysrepo/issues/2627#issuecomment-1455725951   , you can see that we have both applications answering to the get rpc, but then there is an error later when we perform another get on that path.

If you want I can include an untruncated log between the first get and the second one where the error is raised to have more context and to see the edit-config I mentioned which configures the "orusw" to return an error or not on get rpc.

**Comment by michalvasko** [comment]
I have looked at the code and my last (significant) changes of these subscriptions are not yet in `master` (not in the version you are using). So try using the current `devel` branch version of *sysrepo*, it should work there.

**Comment by Krisscut** [comment]
Sure, I will try when I have time to align everything on devel and see how it goes. I will let you know.
Thanks for the support !
