### ISSUE TITLE
RPC action causes sysrepo error: Nested operation "activate" data parent does not exist in the operational datastore.

### ISSUE THREAD

**Issue by pwang111** [sysrepo/sysrepo#2777]
We are implementing the bbf-software-management.yang features and run into some obstacles. We are using the following versions of Netopeer2/Sysrepo versions:

libnetconf2: 2.0.24 (lib so: 2.1.20)
libyang: 2.0.112 (lib so: 2.13.7)
netopeer2: 2.0.35 (lib so: N/A)
sysrepo: 2.0.53 (lib so: 6.4.19)

We are also using a beta version of sysrepo-python/libyang-python that supports 2.x. The following is the most relevant yang involved, which is an augment to the ieft-hardware.yang:

```
module: ietf-hardware
  +--rw hardware
     +--ro last-change?   yang:date-and-time
     +--rw component* [name]
        +--rw name                             string
        ......
        +--rw bbf-swm:software!
        |  +--rw bbf-swm:software* [name]
        |     +--rw bbf-swm:name                            bbf-yang:string-ascii64
        |     +--rw bbf-swm:revisions
        |     |  +--ro bbf-swm:download!
        |     |  |  +---x bbf-swm:download {software-actions}?
        |     |  |     +---w bbf-swm:input
        |     |  |     |  +---w bbf-swm:source
        |     |  |     |  |     +--:(bbf-swm:url)
        |     |  |     +--ro bbf-swm:output
        |     |  |        +--ro bbf-swm:target!
        |     |  |           +--ro bbf-swm:id          uint8
         ……         
        |     |  +--ro bbf-swm:revision* [id]
        |     |  |  +--ro bbf-swm:id                          uint8
        |     |  |    +--ro bbf-swm:activate
        |     |  |       +---x bbf-swm:activate {software-actions}? 
        ……
```
Basically we want to subscribe to software download and activate actions respectively coming from the Netconf client and process them accordingly. 

The following is an example of software download action XML from Netconf client:

```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1001">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>onu_chassis_1</name>
        <software xmlns="urn:bbf:yang:bbf-software-management">
          <software>
            <name>onu-firmware</name>
            <revisions>
              <download>
                <download>
                  <source>
                    <url>http://xx.xx.xx.xx/images/PRX321_SFU_QSPI_PON-squashfs-fullimage.img</url>
                  </source>
                </download>
              </download>
            </revisions>
          </software>
        </software>
      </component>
    </hardware>
  </action>
</rpc>
```

The following is an example of software activate action XML from Netconf client:

```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1001">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>onu_chassis_1</name>
        <software xmlns="urn:bbf:yang:bbf-software-management">
          <software>
            <name>onu-firmware</name>
            <revisions>
              <revision>
                <id>1</id>
                <activate>
                  <activate/>
                </activate>
              </revision>
            </revisions>
          </software>
        </software>
      </component>
    </hardware>
  </action>
</rpc>
```

The following is the python code for action subscription and callbacks:

```python
sw_download_xpath = "/ietf-hardware:hardware/component/bbf-software- 
      management:software/software/revisions/download/download"
sw_activate_xpath = "/ietf-hardware:hardware/component/bbf-software- 
      management:software/software/revisions/revision/activate/activate"

with sysrepo.SysrepoConnection() as connection:
        with connection.start_session(“running”) as session:
               session.subscribe_rpc_call(sw_download_xpath, sw_download_cb)
               session.subscribe_rpc_call(sw_activate_xpath, sw_activate_cb)

def sw_download_cb(xpath: str, input_params: Dict, event: str, private_data: Any) -> Dict:
       if (xpath and event and input_params):
             print("Software download action received for xpath: " + xpath +
                        ", event: " + event + ", input_params: %s" % input_params)
       return {"target": {"id": 1}}

def sw_activate_cb(xpath: str, input_params: Dict, event: str, private_data: Any) -> Dict:
       if (xpath and event and input_params):
           print("Software activate action received for xpath: " + xpath +
                     ", event: " + event + ", input_params: %s" % input_params)
       return None
```	

The software download action is successfully accepted by sysrepo and triggers the callback:

```
Software download action received for xpath: /ietf-hardware:hardware/component[name= onu_chassis_1']/bbf-software-management:software/software[name='onu-firmware']/revisions/download/download, event: rpc, input_params: {'source': {'url': ‘http://xx.xx.xx.xx/images/PRX321_SFU_QSPI_PON-squashfs-fullimage.img’}, 'target': {'selected-by-user': {'operation': 'create'}}}
```

The revision id is also returned as the action output:

```xml
  <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1001">
    <target xmlns="urn:bbf:yang:bbf-software-management">
      <id>1</id>
    </target>
  </rpc-reply>
```

But when Netconf client sends the software activate action request, it fails at sysrepo validation:

```
[ERR]: SR: Nested operation "activate" data parent does not exist in the operational datastore.
[ERR]: NP: Failed to send an RPC (Validation failed).
```
We try to increase the verbose logging but that’s all we get. 

The error message appears to suggest that activate action is missing a parent node, which we guess would be the revision id. We thought returning the output of revision id in software download callback may help that, but apparently that’s not the case. We also tried use set_item() to specifically set the revision id but that failed too. 

So is our guess correct? Revision id is a config=false index of a config=false list, so it is really some operational data only exists in operational datastore. We are a bit confused about this datastore. We have subscribe_module_change() callbacks on the whole ietf-hardware module as well, that makes all the edit-config in this module also setting in the operational datastore as I understand, but those are all config=true data. 

So can someone help with why we succeed in software download action, but fail in the activate action?

**Comment by michalvasko** [comment]
The error message simply informs that [this](https://datatracker.ietf.org/doc/html/rfc8342#section-6.2) requirement is not fulfilled. Check that the parent exists in `operational` by first executing `get-data --datastore operational`.

**Comment by pwang111** [comment]
Thanks for answering my question. Here is the result of get-data:

```
get-data --datastore operational --filter-xpath /ietf-hardware:*
```
```xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
      <name>SFP1-Netopeer2-1</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:transceiver</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>onu-firmware</name>
        </software>
      </software>
    </component>
  </hardware>
</data>
```

```
> get-data --datastore running  --filter-xpath /ietf-hardware:*
```
```xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
      <name>SFP1-Netopeer2-1</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:transceiver</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>onu-firmware</name>
        </software>
      </software>
    </component>
  </hardware>
</data>
```
So does this mean the datastore is missing the revision id? I was suspecting that before and tried to use the set_item() to set the revision id in the download callback but failed. Also tried to use the 'pull' method to return the revision id from the download action output, but that did not help either. How to fix this? I'm new to sysrepo and netconf, some of the concepts are not well understood. Can we set values to the config=false items in the operational datastore? the revision list and all its leafs are config=false, besides using the sr_oper_get_subscribe() to 'pull' them, how to set them otherwise?

**Comment by michalvasko** [comment]
> So does this mean the datastore is missing the revision id?

Yes, that seems to be the problem.

> I was suspecting that before and tried to use the set_item() to set the revision id in the download callback but failed.

That is not such a good idea. With some tweaks it can work but I would advise against it for now.

> Also tried to use the 'pull' method to return the revision id from the download action output, but that did not help either.

I am confused as to what exactly did you try to do but this sounds like something wrong, too.

> I'm new to sysrepo and netconf, some of the concepts are not well understood.

That is fine but you should try to understand the concepts. Read through the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/), especially the Operational Datastore and Operational Data sections are relevant for you now. So, you can set those data in several ways (oper data `pull` or `push` method are both fine) but please, do not do so in any callback but rather in the main program, to avoid several problems.

**Comment by pwang111** [comment]
Thank you for the prompt reply. I'll go over the docs. 

I forgot to mention the same issue with a different action (software download, see my previous post), but only seen in older sysrepo (libsysrepo 1.4.140 (lib so: 5.6.56)). We upgraded from this version recently. This is error we see in the software download action in older sysrepo version:

```
[ERR]: SR: Nested operation "**download**" data parent does not exist in the operational datastore.
[ERR]: NP: Failed to send an RPC (Validation failed).
```
But it works in the newer version (sysrepo: 2.0.53 (lib so: 6.4.19). However, the software activate action does not work under this newer version, as you can also see in my previous post.

```
[ERR]: SR: Nested operation "**activate**" data parent does not exist in the operational datastore.
[ERR]: NP: Failed to send an RPC (Validation failed).
```

Because of this, yesterday I spent sometime looking into the sysrepo source code (2.0.53). It seems that the 'download' action and 'activate' action trigger different 'Module state (flags)' to cause one passes the set count check and the other doesn't:

```c
modinfo.c:

sr_error_info_t *
sr_modinfo_op_validate(struct sr_mod_info_s *mod_info, struct lyd_node *op, int output)
{
    ......
    switch (mod->state & MOD_INFO_TYPE_MASK) {
        case MOD_INFO_REQ:
            ......
            //check set->count, which causes the "Nested operation..." error
        case MOD_INFO_DEP:
           break;   
    ......
}
```
When the 'download' action is sent, the (mod->state & MOD_INFO_TYPE_MASK)=0x0002, which is MOD_INFO_DEP, while the 'activate' action is 0x0008, which is MOD_INFO_REQ.

I'm not sure about the comments on these two values:

```c
#define MOD_INFO_DEP        0x0002 /* dependency module, its data cannot be changed, but are required for validation */
#define MOD_INFO_REQ        0x0008 /* required module, its data can be changed and it will be validated */
```

Why the two actions in the same module trigger different mod_info? Also why the same 'download' action has the same error in older sysrepo, but works in newer one?

I need to add that I know very little of the implementation of sysrepo, this is just the 'hotspot' that I was trying to chase the issue on hand. I could well have missed many important aspects of this, so please correct me if any of above observations are wrong.

**Comment by michalvasko** [comment]
Not sure why you have decided to debug it, you just need to have the parent data in the operational datastore, nothing to do with the actions themselves, which should be working fine. The dependencies make sense, if you look at the actions. `activate` has no input or output so there are no dependencies, while `download` has lots of nodes in input with must, when, and leafref dependencies.

**Comment by pwang111** [comment]
Sorry but I tried setting the parent data but it still failed. Here are the details:

```python
sw_download_xpath = "/ietf-hardware:hardware/component/bbf-software- 
      management:software/software/revisions/download/download"
sw_activate_xpath = "/ietf-hardware:hardware/component/bbf-software- 
      management:software/software/revisions/revision/activate/activate"

with sysrepo.SysrepoConnection() as connection:
        with connection.start_session(“running”) as session:
               session.subscribe_rpc_call(sw_download_xpath, sw_download_cb)
               session.subscribe_rpc_call(sw_activate_xpath, sw_activate_cb)     
               session.subscribe_module_change("ietf-hardware", "/ietf-hardware:hardware/component")

               self.session.switch_datastore("operational");
               self.session.set_item("/ietf-hardware:hardware/component[name=\'SFP1-Netopeer2-1\']")
               self.session.set_item("/ietf-hardware:hardware/component[name=\'SFP1-Netopeer2-1\']/class", "bbf-hardware-types:transceiver")
               self.session.set_item("/ietf-hardware:hardware/component[name=\'SFP1-Netopeer2-1\']/bbf-software-management:software/software[name=\'onu-firmware\']")
              self.session.set_item("/ietf-hardware:hardware/component[name=\'SFP1-Netopeer2-1\']/bbf-software-management:software/software[name=\'onu-firmware\']/revisions/revision[id=1]")
              self.session.apply_changes()
              self.session.switch_datastore("running");
              ......
```
And netopeer2-cli shows things are setting in the operational datastore:

```xml
> get-data --datastore operational --filter-xpath ietf-hardware:*
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
       <name>SFP1-Netopeer2-1</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:transceiver</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>onu-firmware</name>
          <revisions>
            <revision>
              <id>1</id>
            </revision>
          </revisions>
        </software>
      </software>
    </component>
  </hardware>
</data>
```
But same error when sending activate action:

```
[ERR]: SR: Nested operation "activate" data parent does not exist in the operational datastore.
[ERR]: NP: Failed to send an RPC (Validation failed).
```
While sending download action is good.

That's why I went into debugging.

**Comment by michalvasko** [comment]
Looking at the RPC you posted before
```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1001">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>onu_chassis_1</name>
        <software xmlns="urn:bbf:yang:bbf-software-management">
          <software>
            <name>onu-firmware</name>
            <revisions>
              <revision>
                <id>1</id>
                <activate>
                  <activate/>
                </activate>
              </revision>
            </revisions>
          </software>
        </software>
      </component>
    </hardware>
  </action>
</rpc>
```
and the data you have in the `operational` DS
```xml
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
       <name>SFP1-Netopeer2-1</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:transceiver</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>onu-firmware</name>
          <revisions>
            <revision>
              <id>1</id>
            </revision>
          </revisions>
        </software>
      </software>
    </component>
  </hardware>
</data>
```
I would say the error is correct. The parent really does not exist in the `operational` DS, specifically `component` list instance with `name` `onu_chassis_1`.

**Comment by pwang111** [comment]
Sorry, the RPC xml I posted before was from another test. The one that used in here is using the exact same hardware component and software name:

```xml
 <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1001">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>SFP1-Netopeer2-1</name>
        <software xmlns="urn:bbf:yang:bbf-software-management">
          <software>
            <name>onu-firmware</name>
            <revisions>
              <revision>
                <id>1</id>
                <activate>
                  <activate/>
                </activate>
              </revision>
            </revisions>
          </software>
        </software>
      </component>
    </hardware>
  </action>
</rpc>
```
The only difference is I had to add the 'class' leaf in the set_item() call to avoid the 'Mandatory Field Missing' error. 

I can send you the YANGs and the RPC xml to you if you want.

**Comment by michalvasko** [comment]
I see, I have not noticed one important detail seen in the output. There is a parent `activate` container of the action `activate`. More importantly, there is a complex `when` statement on it
```yang
              when "boolean(../../../bbf-swm:capability="
                 + "'bbf-swm:activate')"
                 + " and "
                 + "(../bbf-swm:state='available'"
                 + " or "
                 + "../bbf-swm:state='in-use')"
```
so I would say this condition is not satisfied and hence this action parent really does not exist in the `operational` datastore.

**Comment by pwang111** [comment]
Thanks for pointing out the conditionals. I tried with both conditions satisfied, but still got the same result. Here is the datastore:

```
> get-data --datastore operational --filter-xpath "/ietf-hardware:*"
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
      <name>SFP1-Netopeer2-1</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:transceiver</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>onu-firmware</name>
          <capability xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">bbf-swm:activate</capability>
          <revisions>
            <revision>
              <id>1</id>
              <state>available</state>
            </revision>
          </revisions>
        </software>
      </software>
    </component>
  </hardware>
</data>
```
I hope this covers all the conditions set in when statement.

Here is the debug log output, same result as before:

```
[ERR]: SR: PW: sr_modinfo_op_validate(), output=0, op->schema->nodetype=0400
[ERR]: SR: PW: sr_rpc_send_tree(), input->schema->nodetype=0200
[ERR]: SR: PW: sr_rpc_send_tree(), we are LYS_ACTION
[ERR]: SR: PW: sr_rpc_send_tree(), str=/ietf-hardware:hardware/component[name='SFP1-Netopeer2-1']/bbf-software-management:software/software[name='onu-firmware']/revisions/revision[id='1']/activate/activate
[ERR]: SR: PW: sr_rpc_send_tree(), after sr_get_trim_predicates(), path=/ietf-hardware:hardware/component/bbf-software-management:software/software/revisions/revision/activate/activate
[ERR]: SR: PW: sr_rpc_send_tree(), input != input_op
[ERR]: SR: PW: sr_rpc_send_tree(), parent_path=/ietf-hardware:hardware/component[name='SFP1-Netopeer2-1']/bbf-software-management:software/software[name='onu-firmware']/revisions/revision[id='1']/activate
[ERR]: SR: PW: sr_rpc_send_tree(), mod->name=ietf-hardware, mod->revision=2018-03-13, mod->ns=urn:ietf:params:xml:ns:yang:ietf-hardware, mod->prefix=hw, mod->filepath=/usr/local/sysrepo/yang/ietf-hardware@2018-03-13.yang
[ERR]: SR: PW: sr_shmmod_get_rpc_deps(), shm_rpc->in_deps=0, shm_rpc->in_dep_count=0
[ERR]: SR: PW: sr_rpc_send_tree(), shm_dep_count=0
[ERR]: SR: PW: sr_modinfo_op_validate(), output=0, op->schema->nodetype=0200
[ERR]: SR: PW: sr_modinfo_op_validate(), mod_count loop, i=0
[ERR]: SR: PW: sr_modinfo_op_validate(), (mod->state & MOD_INFO_TYPE_MASK)=0008
[ERR]: SR: PW: sr_modinfo_op_validate(), parent_xpath=/ietf-hardware:hardware/component[name='SFP1-Netopeer2-1']/bbf-software-management:software/software[name='onu-firmware']/revisions/revision[id='1']/activate
[ERR]: SR: PW: sr_modinfo_op_validate(), mod_info->data not null
[ERR]: SR: PW: sr_modinfo_op_validate(), set->count=0
[ERR]: SR: Nested operation "activate" data parent does not exist in the operational datastore.
[ERR]: NP: Failed to send an RPC (Validation failed).
```
Checked the bbf-software-management.yang again, seems no other conditions that I missed.

**Comment by michalvasko** [comment]
Alright, when I had the operational data using `pull` subscription it worked fine but with `push` data I got the same error, which should now be fixed.

**Comment by pwang111** [comment]
Thanks a lot for your prompt response and fix. I tried your fix and tested and it worked.

A general question about fixes, is there a policy for when to release and are there different schemes for major, minor or patch releases?

**Comment by michalvasko** [comment]
The policy is that once I feel there are enough new fixes and/or the last release had been made too long ago, I make a new one :)

**Comment by pwang111** [comment]
Hi Michal (hope I can address you correctly this way). One of my colleagues hit another problem related to software download. From the symptoms it appears coming from libyang. At this point I don't know whether this is just a "is:question" on my side, or something else, so I'm opening another issue thread on that here in sysrepo project. Thanks.
