### ISSUE TITLE
Netopeer server crashing in case of multiple client connections and RPCs handling

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3076]
Hi,

In reference to previous issues raised #2459 and #2820  for sysrepo and netopeer2-server upgrade from initial version 0.7.9 and 0.7.12 respectively to 1.4.122 and 1.1.70 respectively, we were facing the issue that, as per our use case,  when we make multiple netconf connections to same netconf server and each netconf session sends multiple RPCs (like create-subscription, get-config edit-config, that lands parallel on netconf server for different netconf session), we were seeing random RPC timeout issues and eventually netopeer2-server crashed.
We have again tried upgrading to sysrepo (v2.2.36) and netopeer2-server (v2.1.49) and we are seeing the same issue being reproduced with this version as well.  Since this issue was difficult to reproduce somewhere else other than our environment, so as per the discussions on above posts, we have created two scripts through which the issue is easily reproducible.

**netopeer2_cli_wrapper.sh**
```
#!/bin/bash
SCRIPT_PATH=$(pwd)
count=1
while [ $count -le $1 ]
do
  $SCRIPT_PATH/netopeer2_cli_ops.sh $count &
  count=$[$count +1]
done
echo "END OF WRAPPER SCRIPT EXECUTION"
```

**netopeer2_cli_ops.sh**
```
#!/bin/bash
start=`date +%s`
count=1
PID_NS2=$(pidof /usr/local/sbin/netopeer2-server)
while [ -n "$PID_NS2" ]
do
now=$(date)
echo "Executing for client $1 run $count : $now"
netopeer2-cli <<END
connect
subscribe
get-config --source running
END
count=$[$count +1]
PID_NS2=$(pidof /usr/local/sbin/netopeer2-server)
done
end=`date +%s`
echo "END OF OPS SCRIPT EXECUTION FOR CLIENT $1 : `expr $end - $start` seconds"
```

1. The scripts expects that netopeer2-cli and netopeer2-server must be running on the same machine and the script will also be running on the same machine.
2. Netopeer2-cli must have password less ssh connection to netopeer2-server.
3. Both the scripts must be placed in the same directory on the machine and must be given executable permissions.
4. The script netopeer2_cli_wrapper.sh emulates the behaviour of multiple clients that are trying to connect to the same netopeer2 server. The script can emulate any number (taken input as script argument) of concurrent netconf connections. Whereas, the script netopeer2_cli_ops.sh defines what each client do. It creates a netconf connection using netopeer2-cli followed by sending create-subscription RPC followed by get-config RPC. Each client run this cycle again and again till netopeer2 crashes. 

To run the script, please execute below command:-
**For emulating six client connections,**
```
./netopeer2_cli_wrapper.sh 6
```
**For emulating two client connections,**
```
./netopeer2_cli_wrapper.sh 2
```

Few observations to highlight from this latest version testing with the above scripts:-
1. When the script runs for 6 client connections, we see the same RPC timeouts errors mentioned in our old posts and eventually netopeer2 server crashes within 10-15 minutes.
2. When the above runs for 2 client connections, we see the similar error logs in netopeer2 server as seen for 6 client connections but we don't see netopeer2 server crash. However, after sometime, it is observed that netopeer2 cli configuration for auth keys (added for password less ssh) gets randomly erased and the script is not able to make connection to netopeer2 server anymore. What could be the reason for such behaviour?
3. When the above script runs for 1 client connection, everything seems to be working fine and netopeer2 server seems to be stable. 

Since our use case requires multiple netconf connections to be created, it is very important to have netopeer2 stability with this respect. 
By reproducing this issue using our scripts, can we please have an insight as to what could be causing these instability in netopeer2 server for multiple connections and possible fix for this?

Thanks,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Thanks for the scripts, I have really managed to reproduce one data race problem that should now be fixed. I suspect you may have encountered more but those should also be fixed because they were discovered right after the latest release has been made. So, I did not manage to crash the server anymore.

As for the client, I have seen a strange `Bus error` after which the CLI crashed leaving an empty XML configuration file. I suspect that is also what could have happened to you because it would explain why you suddenly could not authenticate using the SSH key, it was no longer present in the configuration. Nevertheless, I think the bus error it may be caused by 2 clients trying to write simultaneously into the same file. CLI definitely does not support multi-instance execution so was to be expected.

So I have found no more problems to fix, let me know if you think there still is something to improve.

**Comment by ChinmayaAgarwal** [comment]
In that case we will try compiling and testing out scenario on master branch. 
Also, is there any tentative date for the next formal release?

Thanks,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
> In that case we will try compiling and testing out scenario on master branch.

You need to use the `devel` branch, `master` is simply the latest release.

> Also, is there any tentative date for the next formal release?

Not really, we usually do one every 2 months. Also, there is quite a lot of changes already so they need to be tested more before the release.

**Comment by ChinmayaAgarwal** [comment]
We compiled both devel and master branch and tested these scripts (with 6 client connections) there and we could see the same issue being reproduced in these branches as well. Below is a screenshot from the issue seen on **devel** branch, after which netopeer2 server eventually crashed:-

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  EV ORIGIN: "rpc" ID 60 processing timed out.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.
```

Thanks,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Please use the current latest *sysrepo* and *netopeer2* from their `devel` branches, there has been a new batch of fixes and improvements. Concurrency has been significantly increased but since there is only a single thread used for handling the notifications, they sometimes time out just like in the error you posted. But the server always recovers and continues to work in my testing.

**Comment by ChinmayaAgarwal** [comment]
Hi,

As suggested, we have compiled the latest devel branch and repeated the mentioned test for 6 simultaneous client connection and we don't see server crashing. We observed it for 2 days. Later on, as per our use case, we scaled up the client connection from 6 to 15 and then repeated the same test and we saw netopeer2 server crashing again within 25 minutes. Below is the dump of the crash.  

```
Thread 7 "netopeer2-serve" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f57cd7b7700 (LWP 1524)]
0x00007f57d5b3637f in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f57d5b3637f in raise () from /lib64/libc.so.6
#1  0x00007f57d5b20db5 in abort () from /lib64/libc.so.6
#2  0x00007f57d5b20c89 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007f57d5b2ea76 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f57d5f202e6 in sr_shmsub_multi_listen_write_event (multi_sub_shm=0x7f57d72df000, valid_subscr_count=2,
    err_code=SR_ERR_OK, shm_data_sub=0x7f57cd7b6810, data=0x0, data_len=0,
    event_desc=0x7f57c400c2c0 "ietf-netconf-notifications", result_str=0x7f57d5f3d8ae "success")
    at /root/sysrepo/src/shm_sub.c:2915
#5  0x00007f57d5f24d35 in sr_shmsub_notif_listen_process_module_events (notif_subs=0x7f57c406b538, conn=0x209acd0)
    at /root/sysrepo/src/shm_sub.c:4546
#6  0x00007f57d5ed7bca in sr_subscription_process_events (subscription=0x7f57c4017c00, session=0x0,
    wake_up_in=0x7f57cd7b6990) at /root/sysrepo/src/sysrepo.c:4519
#7  0x00007f57d5f25428 in sr_shmsub_listen_thread (arg=0x7f57c4017c00) at /root/sysrepo/src/shm_sub.c:4739
#8  0x00007f57d64e317a in start_thread () from /lib64/libpthread.so.0
#9  0x00007f57d5bfbdc3 in clone () from /lib64/libc.so.6
(gdb) 
```
Any pointers as to what could be causing this crash to happen?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Right, just another extreme data race but I reproduced it. If you update *sysrepo* and *netopeer2*, it should be fixed.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We took the checkout of the latest **devel** branch today for sysrepo and netopeer2 and build it. We repeated the same test for 15 simultaneous connections and we still see netopeer2-server crashing with below cdump:-

```
Continuing.
(gdb)
Thread 7 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fee109f7700 (LWP 3333)]
0x00007fee19f455d2 in nc_server_notif_send (session=0x35,
    notif=0x7fedfc0027a0, timeout=1000)
    at /home/ansible/libnetconf2/src/session_server.c:1458
1458        if (!session || (session->side != NC_SERVER) || !nc_session_get_not                                               if_status(session)) {
(gdb) bt
#0  0x00007fee19f455d2 in nc_server_notif_send (session=0x35, notif=0x7fedfc0027a0, timeout=1000)
    at /home/ansible/libnetconf2/src/session_server.c:1458
#1  0x000000000040e1a4 in np_ntf_send (ncs=0x35, timestamp=0x7fee109f6830, ly_ntf=0x7fee109f66b8, use_ntf=0)
    at /home/ansible/netopeer2/src/common.c:354
#2  0x0000000000411ab5 in np2srv_rpc_subscribe_ntf_cb (UNUSED_session=0x7fedfc004030, UNUSED_sub_id=973,
    notif_type=SR_EV_NOTIF_REALTIME, notif=0x7fedfc002250, timestamp=0x7fee109f6830, private_data=0x7fee0403c2a8)
    at /home/ansible/netopeer2/src/netconf.c:849
#3  0x00007fee19130dbc in sr_notif_call_callback (ev_sess=0x7fedfc004030, cb=0x0,
    tree_cb=0x411847 <np2srv_rpc_subscribe_ntf_cb>, private_data=0x7fee0403c2a8, notif_type=SR_EV_NOTIF_REALTIME,
    sub_id=973, notif_op=0x7fedfc002250, notif_ts=0x7fee109f6830) at /home/ansible/sysrepo/src/subscr.c:1734
#4  0x00007fee19165cdb in sr_shmsub_notif_listen_process_module_events (notif_subs=0x7fee0803dda8, conn=0x21b8ce0)
    at /home/ansible/sysrepo/src/shm_sub.c:4518
#5  0x00007fee19117d1a in sr_subscription_process_events (subscription=0x7fee080346b0, session=0x0,
    wake_up_in=0x7fee109f6990) at /home/ansible/sysrepo/src/sysrepo.c:4526
#6  0x00007fee19166592 in sr_shmsub_listen_thread (arg=0x7fee080346b0) at /home/ansible/sysrepo/src/shm_sub.c:4747
#7  0x00007fee1972517a in start_thread () from /lib64/libpthread.so.0
#8  0x00007fee18e3bdc3 in clone () from /lib64/libc.so.6
(gdb)

```

Any pointers as to what could be causing this crash to happen?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
I did manage to reproduce this crash once when I was fixing another dead lock. And after that I could not reproduce it anymore. Actually, after fixing another few dead locks and data races, the server continuously responded to all requests in timely manner when testing it for 15 connections and 15 minutes. So please try the latest `devel` of *sysrepo* and *netopeer2*, I could no longer find any problems whatsoever.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We did try the latest devel branch but we still see the netopeer2 server crashing for multiple as well as single netconf connection (we are firing back to back edit-configs which eventually crashes the netopeer2 server) 

However, due to the instability seen with the latest versions, we have to still work on sysrepo v0.7.9 and netopeer2 v0.7-r2 which seem to be pretty stable for our use case. But we are facing an issue in this version that when we trigger a large number of back to back notifications (using sr_event_notif_send_tree), we see that the available RAM size keeps on decreasing and eventually reaches to a stage that brings sysrepo into the bad state and everything stops working. 

Any pointers here what could be causing this filling up of RAM while sending the notifications and is there any way we can avoid this?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
> Any pointers here what could be causing this filling up of RAM while sending the notifications and is there any way we can avoid this?

No idea, these version are obsolete so I would spend the time on fixing the current versions instead.

> We did try the latest devel branch but we still see the netopeer2 server crashing for multiple as well as single netconf connection (we are firing back to back edit-configs which eventually crashes the netopeer2 server)

So you have another use-case now? Describe it so that I can try it myself, I have not reproduced a crash with the clients with subscriptions.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We compiled the devel branch (as of 21st August) and tried to run the above test again, where in case of one netconf connection, we are firing back to back edit-configs for our custom yang model. The observation is same as before, that eventually after sometime we see netopeer2 server crashing.

We are attaching the file sysrepo_devel_1_connection_test.tar.gz containing the yang model, sample config XMLs and execution script so that this issue can be reproduced at your end.

Below are the details regarding the test execution:-
1. Untar the attached file sysrepo_devel_1_connection_test.tar.gz.
2. Create a folder "/root/scripts" and copy the file/folder dummy_testing/, execute_load.sh, test-router.yang from the untarred folder to "/root/scripts" folder.
3. Install the yang model:-
sysrepoctl --install test-router.yang

4. Configure password less ssh between netopeer2-cli and netopeer2-server on the machine.
5. Start the netopeer2-server.
6. Execute the script "nohup ./execute_load.sh &".

Following the above steps, after sometime we see netopeer2-server crashing. We have taken multiple runs of this test and the observation is same and consistent all the time.

If possible, can we schedule a google meet and I can run you through the detailed issue. I will be more than happy to help debug this issue with you.

Thanks and Regards,
Chinmaya Agarwal.

[sysrepo_devel_1_connection_test.tar.gz](https://github.com/sysrepo/sysrepo/files/12497102/sysrepo_devel_1_connection_test.tar.gz)

**Comment by ChinmayaAgarwal** [comment]
Hi,

We are running the test on Centos 8.4 VM (16 GB RAM and 4 cores)
Below is the gdb backtrace for the netopeer2-server crash:-

```
(gdb) c
Continuing.

Thread 1 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
0x00007f3eb441d6b7 in __strlen_avx2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f3eb441d6b7 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007f3eb49640d7 in lyd_new_opaq2 (parent=0x19d0740, ctx=0x1899480, name=0x7f3eb54def3c "error-message",
    value=0x21 <error: Cannot access memory at address 0x21>, prefix=0x0,
    module_ns=0x7f3eb54de878 "urn:ietf:params:xml:ns:netconf:base:1.0", node=0x7ffde49096e8)
    at /home/ansible/libyang/src/tree_data_new.c:1054
#2  0x00007f3eb54b786c in nc_err_set_msg (err=0x19d0740, error_message=0x21 <error: Cannot access memory at address 0x21>,
    lang=0x4254bc "en") at /home/ansible/libnetconf2/src/messages_server.c:629
#3  0x0000000000409f14 in np2srv_err_reply_sr (err_info=0x1996c10) at /home/ansible/netopeer2/src/main.c:344
#4  0x000000000040a092 in np2srv_rpc_cb (rpc=0x19a2b40, ncs=0x18c0cd0) at /home/ansible/netopeer2/src/main.c:392
#5  0x00007f3eb54c999b in nc_server_send_reply_io (session=0x18c0cd0, io_timeout=10, rpc=0x19b5200)
    at /home/ansible/libnetconf2/src/session_server.c:1524
#6  0x00007f3eb54ca51f in nc_ps_poll (ps=0x18545f0, timeout=10, session=0x7ffde49099b0)
    at /home/ansible/libnetconf2/src/session_server.c:1884
#7  0x000000000040c52e in worker_thread (arg=0x187d960) at /home/ansible/netopeer2/src/main.c:1039
#8  0x000000000040d4d7 in main (argc=1, argv=0x7ffde4909c48) at /home/ansible/netopeer2/src/main.c:1413
(gdb)

```

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
I see. Could you please provide the stack trace of all the threads at the moment of this crash? Thanks.

**Comment by ChinmayaAgarwal** [comment]
Hi,

Please find below stack trace for the all the threads after the crash:-

```
(gdb) info threads
  Id   Target Id                                          Frame
* 1    Thread 0x7fe71eaf0bc0 (LWP 1546) "netopeer2-serve" 0x0000000000409e89 in np2srv_err_reply_sr (err_info=0x0)
    at /home/ansible/netopeer2/src/main.c:324
  2    Thread 0x7fe71853c700 (LWP 1547) "netopeer2-serve" 0x00007fe71d38f29f in select () from /lib64/libc.so.6
  3    Thread 0x7fe717d3b700 (LWP 1548) "netopeer2-serve" 0x00007fe71d38f29f in select () from /lib64/libc.so.6
  4    Thread 0x7fe71753a700 (LWP 1549) "netopeer2-serve" 0x00007fe71d38f29f in select () from /lib64/libc.so.6
  5    Thread 0x7fe716d39700 (LWP 1550) "netopeer2-serve" 0x00007fe71d38f29f in select () from /lib64/libc.so.6
  6    Thread 0x7fe716538700 (LWP 1551) "netopeer2-serve" 0x00007fe71dc8e0b0 in nanosleep () from /lib64/libpthread.so.0
  7    Thread 0x7fe715d37700 (LWP 1552) "netopeer2-serve" 0x00007fe71dc8e0b0 in nanosleep () from /lib64/libpthread.so.0


(gdb) thread apply all bt

Thread 7 (Thread 0x7fe715d37700 (LWP 1552)):
#0  0x00007fe71dc8e0b0 in nanosleep () from /lib64/libpthread.so.0
#1  0x000000000040d971 in np_sleep (ms=200) at /home/ansible/netopeer2/src/common.c:80
#2  0x000000000040c551 in worker_thread (arg=0x1dcf350) at /home/ansible/netopeer2/src/main.c:1043
#3  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#4  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7fe716538700 (LWP 1551)):
#0  0x00007fe71dc8e0b0 in nanosleep () from /lib64/libpthread.so.0
#1  0x000000000040d971 in np_sleep (ms=200) at /home/ansible/netopeer2/src/common.c:80
#2  0x000000000040c551 in worker_thread (arg=0x1cd0890) at /home/ansible/netopeer2/src/main.c:1043
#3  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#4  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7fe716d39700 (LWP 1550)):
#0  0x00007fe71d38f29f in select () from /lib64/libc.so.6
#1  0x00007fe71d6c2eae in sr_shmsub_listen_thread (arg=0x1c52770) at /home/ansible/sysrepo/src/shm_sub.c:4753
#2  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#3  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fe71753a700 (LWP 1549)):
#0  0x00007fe71d38f29f in select () from /lib64/libc.so.6
#1  0x00007fe71d6c2eae in sr_shmsub_listen_thread (arg=0x1da3bc0) at /home/ansible/sysrepo/src/shm_sub.c:4753
#2  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#3  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fe717d3b700 (LWP 1548)):
#0  0x00007fe71d38f29f in select () from /lib64/libc.so.6
#1  0x00007fe71d6c2eae in sr_shmsub_listen_thread (arg=0x1c8b2e0) at /home/ansible/sysrepo/src/shm_sub.c:4753
#2  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#3  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--

Thread 2 (Thread 0x7fe71853c700 (LWP 1547)):
#0  0x00007fe71d38f29f in select () from /lib64/libc.so.6
#1  0x00007fe71d6c2eae in sr_shmsub_listen_thread (arg=0x1d81850) at /home/ansible/sysrepo/src/shm_sub.c:4753
#2  0x00007fe71dc8417a in start_thread () from /lib64/libpthread.so.0
#3  0x00007fe71d397dc3 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fe71eaf0bc0 (LWP 1546)):
#0  0x0000000000409e89 in np2srv_err_reply_sr (err_info=0x0) at /home/ansible/netopeer2/src/main.c:324
#1  0x000000000040a092 in np2srv_rpc_cb (rpc=0x1c56af0, ncs=0x1cd0310) at /home/ansible/netopeer2/src/main.c:392
#2  0x00007fe71e4a499b in nc_server_send_reply_io (session=0x1cd0310, io_timeout=10, rpc=0x1d7f9f0)
    at /home/ansible/libnetconf2/src/session_server.c:1524
#3  0x00007fe71e4a551f in nc_ps_poll (ps=0x1c645f0, timeout=10, session=0x7ffe6e208050)
    at /home/ansible/libnetconf2/src/session_server.c:1884
#4  0x000000000040c52e in worker_thread (arg=0x1c8d960) at /home/ansible/netopeer2/src/main.c:1039
#5  0x000000000040d4d7 in main (argc=1, argv=0x7ffe6e2082e8) at /home/ansible/netopeer2/src/main.c:1413
(gdb)

```

Thanks and Regards,
Chinmaya Agarwal

**Comment by michalvasko** [comment]
Okay, it does not seem to be a threading issue so I really cannot help. You suggested a call to do a remote debugging session so we can do that, I guess. But you could also provide one last piece of information, what is the error printed just before the crash at [main.c:388](https://github.com/CESNET/netopeer2/blob/devel/src/main.c#L388)? It is unlikely to allow me to fix the problem but would definitely provide relevant information.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We have run the above mentioned tests (with test-router.yang) on two variants i.e latest devel branch and stable release netopeer2 v2.1.71, sysrepo v2.2.105. We tried to push 60000 records in the data tree but we could manage to push only 21000 and 17000 records on devel and stable versions respectively, and start observing below errors:-

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  EV ORIGIN: "rpc" ID 16896 processing timed out.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.
```

Once this error comes, eventually we see below error continuously:-
```
nc ERROR: Received a <rpc-reply> with an unexpected message-id 59976 (expected 59982).
cli_send_recv: Unexpected reply received - ignoring and waiting for the correct reply.
cli_send_recv: Timeout for receiving a reply expired.
```

However, we see netopeer2 server crashing on the devel branch but we don't see the crash in stable release version.

Thanks and Regards,
Chinmaya Agarwal

**Comment by ChinmayaAgarwal** [comment]
Sorry, marked the issue completed by mistake. I have reopened it.

**Comment by michalvasko** [comment]
Could you provide all the YANGs, data, and the code to reproduce it? The timeout may be expected but the crash is not.

**Comment by ChinmayaAgarwal** [comment]
We have executed the exact same test using the same script, yang model and files as mentioned in below comment:-



> Hi,
> 
> We compiled the devel branch (as of 21st August) and tried to run the above test again, where in case of one netconf connection, we are firing back to back edit-configs for our custom yang model. The observation is same as before, that eventually after sometime we see netopeer2 server crashing.
> 
> We are attaching the file sysrepo_devel_1_connection_test.tar.gz containing the yang model, sample config XMLs and execution script so that this issue can be reproduced at your end.
> 
> Below are the details regarding the test execution:-
> 
> 1. Untar the attached file sysrepo_devel_1_connection_test.tar.gz.
> 2. Create a folder "/root/scripts" and copy the file/folder dummy_testing/, execute_load.sh, test-router.yang from the untarred folder to "/root/scripts" folder.
> 3. Install the yang model:-
>    sysrepoctl --install test-router.yang
> 4. Configure password less ssh between netopeer2-cli and netopeer2-server on the machine.
> 5. Start the netopeer2-server.
> 6. Execute the script "nohup ./execute_load.sh &".
> 
> Following the above steps, after sometime we see netopeer2-server crashing. We have taken multiple runs of this test and the observation is same and consistent all the time.
> 
> If possible, can we schedule a google meet and I can run you through the detailed issue. I will be more than happy to help debug this issue with you.
> 
> Thanks and Regards, Chinmaya Agarwal.
> 
> [sysrepo_devel_1_connection_test.tar.gz](https://github.com/sysrepo/sysrepo/files/12497102/sysrepo_devel_1_connection_test.tar.gz)

**Comment by michalvasko** [comment]
I have ran it the whole night and got to more than 28000 records and could only see timeouts, you can "fix" those by increasing the server timeout `netopeer2-server -t 60` and maybe even CLI timeout by adding `--rpc-timeout=60` to a command.

So, please run the server with `gdb` and provide the stacktrace when it crashes, I am not able to reproduce.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We are running the tests with the increased timeout value, meanwhile were trying password less ssh between netopeer2-server and netopeer2-cli using the authorized keys approach but could not make it work. How can we make password less ssh work with the latest devel branch?

Thanks and Regards, 
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
I have added an [example config file](https://github.com/CESNET/netopeer2/blob/devel/example_configuration/ssh_listen.xml) that should help with understanding the latest changes in *netopeer2* configuration, please take a look at it.

**Comment by jktjkt** [comment]
Is it possible to provide an example config which enables the "whatever succeeds first" configuration and delegates everything to the system config? I.e., if the client provides an SSH key, delegate that to the pubkeys read from the filesystem, and if there's no key, enable both keyboard-interactive and password (the choice of these is done by the client anyway), and delegate both of these to PAM internally? I'm asking because the comments in the example suggest to me that this is an alternative, either the keys, or the system passwords, or the system kbd-interactive.

**Comment by michalvasko** [comment]
Yes, the comments are correct and this is how the YANG is modeled meaning you generally set only one specific authentication method that must be used. If you configure several methods, [all of them](https://github.com/CESNET/libnetconf2/blob/b329fef3b3562acd9d16955dc69059c983b0f904/modules/ietf-ssh-server%402023-04-17.yang#L253) must succeed one after the other for the client to authenticate.

**Comment by jktjkt** [comment]
Could you please add an option to libnetconf2/Netopeer2 which would mimic the default config of essentially any Linux system over the past 20 years, that is, allow any and all of these methods?

**Comment by michalvasko** [comment]
I think we are getting off-topic and should stop. Before making any changes I would instead suggest you write into the NETCONF mailing list and ask about these designing decisions while presenting your opinion as well.

**Comment by ChinmayaAgarwal** [comment]
I made below configuration changes to make password less ssh work on devel branch but it showing me error while connecting:-

1.
[root@localhost ~]# netopeer2-cli 
> auth pref publickey 1
> auth pref interactive 0
> auth pref password 0

2. Created a load.xml having ietf-netconf-server subtree with below modified content:-
  <client-authentication>
              <users>
                <user>
                  <name>root</name>
                  <public-keys>
                  <use-system-keys xmlns="urn:cesnet:libnetconf2-netconf-server"/>
                   </public-keys>
                </user>
              </users>
   </client-authentication>

and content of authorized_keys has the key of the machine
[root@localhost ~]# cat .ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCx0StSGK7vytdwHQBzKLIxICl6/Q9UaB/8/Po17F98sfrDXDwLdKKgov/8slJQz2/p32fhKMjTn4grr19CTgOv24cmTZD1VNS3uz/kyRlHlIBPZ65wCaAjjtMur1+CcTXbTGi+41YOq5mpw8Xwknjxjy5NyjSEcwrGdpXjcqnDgF2ITr8R2iN1Q8V2t7EXkDobaNgCtqZW9vFSWKhFTnMYzGlDMoFkxGiocBzYtacoedSzYciV9n3GMmJZwm5afLrVnCKO9+lyjZNCtmAJ39FH3RHh5P4nXxvt12Z5+6il1bX6qktCAaMB2A4edfa6K2BomcUo/H2ATiG6poL3ARfJNxPxim+99n61Yl9sfEFQ/xZu9yVqKxxIDM1L9fo55k8lhN/ncdsZ7BVwat8xIAI6t23h3RmFekDksC519D9F1cfqUiHdYb51pvpFxdM8a1n/GUCMTDwVbDvP4enKdxrDW5XljvsS0uBanuf5ecWAtIW5C0Lg0ISfcBpruEPWHJk= root@localhost.localdomain
[root@localhost ~]#

and then we loaded the configuration
[root@localhost ~]# sysrepocfg --import=load.xml --datastore running --module ietf-netconf-server
[root@localhost ~]# sysrepocfg --import=load.xml --datastore startup --module ietf-netconf-server

After this we restarted the netopeer2-server and when we tried connecting, we are seeing this error:-
[root@localhost ~]# netopeer2-cli
> connect
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
>
Are we missing anything here?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Run the server with `-v2` and look at its output.

**Comment by ChinmayaAgarwal** [comment]
Getting below output:-
[INF]: LN: Accepted a connection on 0.0.0.0:830 from 127.0.0.1:59624.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[2024/01/08 19:25:40.532324, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: LN: Communication SSH socket unexpectedly closed.

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Meaning the client did not even attempt to authenticate, increase the verbosity of the client then. Run `verb 2` before calling `connect`.

**Comment by ChinmayaAgarwal** [comment]
Saw below error:-
```
> verb 2
> connect
nc VERBOSE: Trying to connect via IPv6 to ::1:830.
nc VERBOSE: getsockopt() error (Connection refused).
nc VERBOSE: Trying to connect via IPv4 to 127.0.0.1:830.
nc VERBOSE: Successfully connected to localhost:830 over IPv4.
[2024/01/08 19:29:50.267366, 1] ssh_config_parse_line:  line 3: Unsupported Match keyword 'final', skipping
[2024/01/08 19:29:50.267675, 1] ssh_config_parse_line:  Unknown option: GSSAPIKexAlgorithms, line: 3
[2024/01/08 19:29:50.267780, 1] ssh_config_parse_line:  Unknown option: CASignatureAlgorithms, line: 6
[2024/01/08 19:29:50.267833, 2] ssh_config_parse_line:  Unapplicable option: ForwardX11Trusted, line: 12
[2024/01/08 19:29:50.267865, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 15
[2024/01/08 19:29:50.267886, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 16
[2024/01/08 19:29:50.267918, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 17
[2024/01/08 19:29:50.267941, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 18
[2024/01/08 19:29:50.267980, 2] ssh_connect:  libssh 0.9.7 (c) 2003-2021 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[2024/01/08 19:29:50.268009, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2024/01/08 19:29:50.268047, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2024/01/08 19:29:50.374912, 2] ssh_client_connection_callback:  SSH server banner: SSH-2.0-libssh_0.9.7
[2024/01/08 19:29:50.374959, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.9.7
[2024/01/08 19:29:50.375102, 1] ssh_known_hosts_read_entries:  Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
[2024/01/08 19:29:50.375189, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,rsa-sha2-512,aes256-gcm@openssh.com,aes256-gcm@openssh.com,aead-gcm,aead-gcm,none,none,,
[2024/01/08 19:29:50.381944, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2024/01/08 19:29:50.381967, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2024/01/08 19:29:50.381988, 2] ssh_packet_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
[2024/01/08 19:29:50.381997, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2024/01/08 19:29:50.382080, 2] ssh_packet_newkeys:  Signature verified and valid
[2024/01/08 19:29:50.384745, 1] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey
[2024/01/08 19:29:50.384767, 2] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can continue: publickey
nc VERBOSE: Publickey athentication.
nc VERBOSE: No key pair specified.
nc WARNING: Authentication denied.
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
>
```

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
There you have it, you have not configured any public keys for the CLI. Use `auth keys add <public_key_path> <private_key_path>` to add one pair.

**Comment by ChinmayaAgarwal** [comment]
Hi,

We have run the same test, mentioned above, again with changed netopeer2/sysrepo timeout values (netopeer2-server -t 60). 
In previous test runs (with default timeout values), we use to get below errors:-
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  EV ORIGIN: "rpc" ID 16896 processing timed out.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.
``` 

followed by

```
nc ERROR: Received a <rpc-reply> with an unexpected message-id 59976 (expected 59982).
cli_send_recv: Unexpected reply received - ignoring and waiting for the correct reply.
cli_send_recv: Timeout for receiving a reply expired.
```

but in the latest run (with the changed timeout values), we got below error directly, though we do see edit-config getting success after that as well:-
```
nc ERROR: Received a <rpc-reply> with an unexpected message-id 38199 (expected 38200).
cli_send_recv: Unexpected reply received - ignoring and waiting for the correct reply.
cli_send_recv: Timeout for receiving a reply expired.

```

What is the reason for this error, before and after increasing the timeouts and how can we resolve this?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
You need to increase the timeout for waiting for a rpc-reply, by adding `--rpc-timeout 60` (for example) to CLI commands.
