### ISSUE TITLE
bbf-software-management.yang delete action successfully executed, but revision-deleted alarm is not sent

### ISSUE THREAD

**Issue by patilsoumya5** [sysrepo/sysrepo#3091]
Hi Team,

Current sysrepo version we are using : sysrepo-2.2.12

We have successfully downloaded the image, and tried to delete it. Perhaps image has been deleted, and alarm for revision-deleted notification is not received, libyang throws below error.

```
libyang[0]: Internal error (/home/karthik/docker-ONL/OpenNetworkLinux/soumya/onu-upgrade/latest/latest/opensource_netconf_polt/build/third_party/libyang/libyang-2.1.4/src/path.c:482).
[1451671: D NETCONF             ] bcmolt_netconf_module_utils.c 491|
lyd_new_path(NULL, ctx, "/id", "1", 0, 0) -> NULL
[1451671: E NETCONF             ] bcmolt_netconf_module_utils.c 494|
Error 'Internal error (/home/karthik/docker-ONL/OpenNetworkLinux/soumya/onu-upgrade/latest/latest/opensource_netconf_polt/build/third_party/libyang/libyang-2.1.4/src/path.c:482).'. Fail
[1451671: E NETCONF             ] bbf-xpon-onu-upgrade.c 1934| Failed to send notification for component = ont1 image = zyxel_older_version.bin
```

Same issue seen when we try from examples of sysrepo code :

```
/sysrepo/sysrepo-2.2.12/build/examples# ./notif_send_example "/ietf-hardware:hardware/component[name='ont1']/bbf-software-management:software/software[name='zyxel_older_version.bin']/revisions/revision-deleted" id 1
Application will send notification "/ietf-hardware:hardware/component[name='ont1']/bbf-software-management:software/software[name='zyxel_older_version.bin']/revisions/revision-deleted".

Creating value "id" failed.
[root@zyxelbuild:/home/karthik/docker-ONL/OpenNetworkLinux/soumya/onu-upgrade/latest/latest/opensource_netconf_polt/build/third_party/sysrepo/sysrepo-2.2.12/build/examples#](mailto:root@zyxelbuild:/home/karthik/docker-ONL/OpenNetworkLinux/soumya/onu-upgrade/latest/latest/opensource_netconf_polt/build/third_party/sysrepo/sysrepo-2.2.12/build/examples)
```

Please help.

Thanks,
Soumya

**Comment by michalvasko** [comment]
The internal error should be fixed but the path you are using in the first case is simply wrong. Either use the full absolute path or specify the context node for a relative path. The second case should be correct but there was a problem in the code, should work in the latest *sysrepo* `devel` branch.

**Comment by patilsoumya5** [comment]
LY_PATH_PREFIX_FIRST is not defined in our tgz, can you please tell us what is the value against LY_PATH_PREFIX_FIRST.

**Comment by patilsoumya5** [comment]
with given fix also this issue is still observed, please help.

**Comment by michalvasko** [comment]
With the current *sysrepo* `devel`:
```
> examples/notif_send_example "/ietf-hardware:hardware/component[name='ont1']/bbf-software-management:software/software[name='zyxel_older_version.bin']/revisions/revision-deleted" id 1
Application will send notification "/ietf-hardware:hardware/component[name='ont1']/bbf-software-management:software/software[name='zyxel_older_version.bin']/revisions/revision-deleted".

[ERR] Nested operation "revision-deleted" data parent does not exist in the operational datastore.
Failed to send the notification.
```

**Comment by patilsoumya5** [comment]
can you please provide patch, given patch [https://github.com/CESNET/libyang/commit/074d9a161b6dd2311f53863cc4391ce47f961734] didnt work, we applied locally and tried.

**Comment by michalvasko** [comment]
If that patch did not work, I cannot help you, I do not know what other commits would be required for the use-case to work. I could only find out the same way you would, by trying newer versions and checking whether it works there or not.
