### ISSUE TITLE
sysrepoctl core dump during installing a yang file with two 'augment' syntax

### ISSUE THREAD

**Issue by WinterZheng** [sysrepo/sysrepo#671]
The sysrepoctl crashed when installing a yang file with two 'augment' syntax. Bellow is the error logs.

> tester@Wzheng build % sysrepoctl --install --yang=/home/tester/ports.yang 
> Installing a new module from file '/home/tester/ports.yang'...
> Installing the YANG file to '/home/tester/3rd/sysrepo/build/repository/yang/ports.yang'...
> Installing data files for module 'ports'...
> [1]    10672 segmentation fault (core dumped)  sysrepoctl --install --yang=/home/tester/ports.yang

Here is the yang file ports.yang :
```YANG
module ports {
    namespace "http://example.com/ns/ports";
    prefix ports;

    container ports {
        list port {
            key name;
            leaf name {
                type string;
            }
            leaf rate {
                type uint32;
            }
        }
    }

    augment "/ports/port" {
        when "name = 'input'";
        leaf input-power {
            type int32;
        }
    }

    augment "/ports/port" {
        when "name = 'output'";
        leaf output-power {
            type int32;
        }
    }

}
```
The core dump happened in the function 'md_traverse_schema_tree' in the 'module_dependencies.c'.  

next_node:
            /* backtracking + automatically moving to the next sibling if there is any */
            if (node != root) {

The 'input-power' node's next sibling node is 'output-power', and they have the same parent node name '/ports/port'. But the address of 'node' pointer and 'root' pointer is different in this case.

**Comment by lukasmacko** [comment]
fixed (unreproducible) with the latest devel branch

**Comment by morganzhh** [comment]
Hi

I am afraid is's not solved, the reason for this bug is invalid data access, the test survived in my Ubuntu  VM but not in my Alpine Linux VM.

When the node is Augment, the ``lys_node.next`` is really ``lys_node_augment.when``, which don't have 'module', so when  ``LYS_MAIN_MODULE(node->next)`` get called, the behavior will be unknown.

```c
#define LYS_MAIN_MODULE(lys_elem)  \
            (lys_elem->module->type ? ((struct lys_submodule *)lys_elem->module)->belongsto : lys_elem->module)
```

```c
struct lys_node_augment {
  
    /* replaces #next and #prev members of ::lys_node */
    struct lys_when *when;           /**< when statement (optional) */
    struct lys_node *target;         /**< pointer to the target node */

};
```

```c
struct lys_when {
    const char *cond;                /**< specified condition (mandatory) */
    const char *dsc;                 /**< description (optional) */
    const char *ref;                 /**< reference (optional) */
};
```

This is the log output when I add code below

```diff
diff --git a/src/module_dependencies.c b/src/module_dependencies.c
index 7ec3693..d1f8db5 100644
--- a/src/module_dependencies.c
+++ b/src/module_dependencies.c
@@ -1742,6 +1742,11 @@ md_traverse_schema_tree(md_ctx_t *md_ctx, md_module_t *module, struct lys_node *
 next_node:
             /* backtracking + automatically moving to the next sibling if there is any */
             if (node != root) {
+                if (LYS_AUGMENT == node->nodetype)
+                {
+                    SR_LOG_ERR("Node %s is Augment, Next node name [%s] dsc %s ref %s", node->name, node->next->name, node->next->dsc?node->next->dsc:"None", node->next->ref?node->next->ref:"None");
+                }
+
                 if (node->next && main_module_schema == LYS_MAIN_MODULE(node->next)) {
                     node = node->next;
                     process_children = true;
```

```
sysrepoctl --install --yang /usr/yang/test.yang
Installing a new module from file '/usr/yang/test.yang'...
Installing the YANG file to '/etc/sysrepo/yang/ports.yang'...
Installing data files for module 'ports'...
[ERR] Node /ports/port is Augment, Next node name [name = 'output'] dsc None ref None
Segmentation fault
```

Could help solve this issue, because ```augment``` is used everywhere in our ``yang`` files

**Comment by rkrejci** [comment]
Should be fixed now in devel (98315fd)
